### ISSUE TITLE
Can't restore wallet

### ISSUE THREAD

**Issue by MaxHillebrand** [Blockstream/green_android#1]
### Description

After typing in the 24 word mnemonic and clicking OK, the error `login failed` pops up.

### Version

[Green v3.0.6](https://github.com/Blockstream/green_android/tree/release_3.0.6)

### Steps to reproduce

Type in 24 words, press OK. Same error in both main net and testnet, with and without tor.

### Expected behaviour

Accept mnemonic and continue with the wallet setup process.

### Actual behaviour

Login failed, no further process.

### Device or machine

One Plus 3, Android v8.0.0, OxygenOS v5.0.8

### Additional info

Great wallet, keep it up!

**Comment by greenaddress** [comment]
Where is the mnemonic coming from? Was it a mnemonic of a Green wallet that completed the onboarding process?

**Comment by MaxHillebrand** [comment]
Yes, I successfully generated a new seed in Green wallet main net, and want to import that same seed on the testnet wallet as well.

**Comment by greenaddress** [comment]
The same seed could be used in testnet (we don't advice for it for privacy reasons) but to do that you'd either need to use the API or work around it by putting the mnemonic temporarily on a hardware wallet - hardware wallet automatically register with the pub keys on given by the trezor - they do automatic onboarding so to speak.

**Comment by MaxHillebrand** [comment]
Ok, I've tried the same with a 24 word [no password] seed generated on electrum testnet. Same error as described above.

**Comment by greenaddress** [comment]
This is expected behavior but we do want to improve the error message and allow users to use externally generated seeds (but we do not advice to reuse the seed across wallets)
