### ISSUE TITLE
Include 'sats' denomination

### ISSUE THREAD

**Issue by vindard** [Blockstream/green_android#10]
Under the `Settings -> Account -> Bitcoin denomination` menu right now the options are:
* BTC
* mBTC
* μBTC
* bits

It would be great to also have a **sats¹** option given the recent growing popularity of the denomination associated with the Lightning Network and the availability of this option in other popular wallet apps and UIs.

---
¹ _satoshis, where `1 BTC == 10^8 sats`_

**Comment by greenaddress** [comment]
We'll add it!

**Comment by bitcoinuser** [comment]
Can be closed as it was implemented.

**Comment by vindard** [comment]
True, looks like it was added at [commit #1f01b20](https://github.com/Blockstream/green_android/commit/1f01b204967cbec340a95354eb8c342035539e03). Closing now.
