### ISSUE TITLE
The Tx Failed the testmempoolaccept call with the node. 

### ISSUE THREAD

**Issue by jumanjicraze** [Blockstream/green_android#100]
### Description
The Tx Failed the testmempoolaccept call with the node. 
This error is showing up when trying to create a transaction

### Version
Latest version of app on playstore.

### Steps to reproduce
Create a transaction ( Send Btc)

**Comment by domegabri** [comment]
Hello @jumanjicraze , we had several reports of this issue and we are working on a fix; can you confirm this is still happening for you? if this is still affecting your wallet, do you mind reporting at info@greenaddress.it so that our support team can handle it?

**Comment by domegabri** [comment]
Hello, we believe this has been fixed. Please let us know if this is not the case for your wallet.
