### ISSUE TITLE
Feature request: Add method to share the QR code (image)

### ISSUE THREAD

**Issue by sgornick** [Blockstream/green_android#101]
### Description

There appears to currently be no way to share the QR code (image), only the text / characters.  This would be useful when using Blockstream Green but needing to share the QR code with the (receiving) address in order to receive payment.

The specific use case today where I encountered this is where I did a P2P trade on HodlHodl where I am selling on-chain bitcoin, and the buyer is paying with Liquid Bitcoin (L-BTC).   I sent the text / address but the buyer saw the address on their laptop.  That person wants to pay from their Blockstream Green wallet but I could provide no QR code.  I figured I could do a screen shot of the Receive screen which had the QR code, but my Android tells me I cannot -- screen shots are disabled by the app or my administrator.   If I could simply send the QR code (as an image), then I could have resolved that.   Essentially, this was a deal killer and the buyer stopped responding after a short while, and the P2P trade expired. 

### Version

v3.4.0 on Android

### Steps to reproduce

From wallet, press Receive.  Hold press the QR code.

### Expected behaviour

Some method to copy the QR code image to clipboard, or send, the QR code. 

### Actual behaviour

"Address copied to clipboard" flash message.  

### Screenshots

LOL, no ... results in Android System message:
"Couldn't capture screenshot"
"Taking screenshots isn't allowed by the app or your org..."

### Device or machine

Android 8.1.0

### Additional info

I could see this resolved maybe with something like a short press used to copy the text.  A long press used to copy the image.    I don't know that the "Share Address" button needs to support this -- the long press to clipboard might be sufficient.

**Comment by angelix** [comment]
@sgornick feature implemented.
