### ISSUE TITLE
face unlock for pixel users

### ISSUE THREAD

**Issue by bingoxo** [Blockstream/green_android#103]
Since some google pixel phones don't have fingerprint scanners and have face scanner instead it would be great to have that biometric used in your app

Edit : hope this helps : https://android-developers.googleblog.com/2019/10/one-biometric-api-over-all-android.html
https://developer.android.com/codelabs/biometric-login#0
https://android-developers.googleblog.com/2020/09/lockscreen-and-authentication.html

**Comment by angelix** [comment]
@bingoxo fixed in latest release.
