### ISSUE TITLE
CSV timelock expiration 2-of-2 account

### ISSUE THREAD

**Issue by screweduser** [Blockstream/green_android#113]
### Description

Yes, I lost my ONLY 2fa method, the email code does not arrive... 
Should I just wait for the CSV expiration and ignore any redeposit notification to be able to spend my funds again?
It will be necessary to request a 2fa reset or can I avoid this step?

### Additional info

Not 100% clear in the Blockstream help center. Support team does not answer this.

**Comment by jgriffiths** [comment]
Hi @screweduser our support may be a little overloaded right now due to current market conditions. If your UTXOs are in CSV addresses (i.e. they were received after your wallet was upgraded to CSV), then once the CSV timelock expires you can use ga_recovery to spend them elsewhere. This will be the fastest method since you can move the coins as soon as the CSV timelock is expired. The only downsides are that you will need to move the coins to an address you control, which will cost you transaction fees, and your current wallet will still be locked (although you can create another or use another wallet of course).

Otherwise, you can initiate the reset process which will give you control of the wallet in ~12 months without having to move the coins.

If you reset or move the coins to another Green wallet, please ensure you set up an additional two-factor method as a backup to prevent this happening again. If you still have access to your email but emails are not arriving, and are not in your spam folder, please contact your email provider to see if they are blocking the emails upstream from your account  (this happens sometimes for some organizations such as universites/workplaces).

**Comment by screweduser** [comment]
Thank you for your input !

UTXOs are from last week, CSV surely.I'm afraid I'm going to request the
2FA reset since I'm not an advanced user to use garecovery.

My concern with 2FA reset is the total waiting, since previous nLocktime
adds remaining days until expiration, to the grace period of the 2FA reset.
In my case that would represent 2 years, I hope that's not the  CSV case.

**Comment by jgriffiths** [comment]
@screweduser under CSV the wait time should be a fixed 12 months. We will shortly be rolling out functionality to undo a two-factor reset, so if you change your mind in the future or we add support for spending expired CSV without two-factor before your wait period expires, then you can undo your reset and just spend the coins from the wallet directly in the best case.

**Comment by screweduser** [comment]
That would be great, thank you.

I did the reset sadly, and says 719 days left, I want to cry right now. I'm
trying to restore my previous protonmail account, now blacklisted.

Any other alternative maybe? I have screens from my two transactions, even
from the sent side to my Green wallet.

**Comment by jgriffiths** [comment]
@screweduser Please don't panic; the functionality to undo a reset will be released soon (within the next month I think). I'll have a look at why the csv locktime is being included in your wait, its possible we can reduce your wait time once I resolve this behaviour - please watch for mentions here.

**Comment by screweduser** [comment]
Thanks for your reply, I will wait for the next improvements, even 12
months sounds good in this instance.

**Comment by jgriffiths** [comment]
Hi @screweduser undo 2fa reset is now available in the android wallet (once its accepted in the play store, over the next few days) and will be available in the next releases of the ios and desktop wallets, which should be in a couple of weeks. I suggest you undo the reset for now.

I am hoping to update the reset period for csv wallets to be the date that the last utxo expires, once this is implemented you will be able to re-request the reset and have a much shorter waiting period. We should also be allowing spending of expired utxos without 2fa sometime in the coming months.

**Comment by screweduser** [comment]
Thanks for the follow-up, I will cancel the 2fa reset in the next update and look forward to subsequent updates!

**Comment by screweduser** [comment]
Hello,
Finally I installed the latest version of Green and it happens that to cancel the 2fa reset I need my previous 2fa method, the only one that I had set and that I lost.
I think the wait is going to be unavoidable, except that both csv and 2fa deadlines can overlap somehow.

![IMG_20210506_232138](https://user-images.githubusercontent.com/81266001/117390251-302cd680-aec4-11eb-94d6-1bf58546c3ee.jpg)

**Comment by jgriffiths** [comment]
Hi @screweduser there are two operations, cancelling a reset via providing 2FA, and undoing a reset that you initiated which only requires access to the email that you used to perform the reset. The latter is what you want, I believe this is available in the desktop wallet now and should be in the mobile wallets soon.

**Comment by screweduser** [comment]
Ok now I get it, that would make sense.

**Comment by screweduser** [comment]
I tried to login into the wallet after latest update, and shows a time out error. Last time showed about 250 remaining days.

Now I can't even login or found the wallet if i try to restore it in other device... Why would this happend?

![IMG_20220719_184134](https://user-images.githubusercontent.com/81266001/179854704-7edf5c66-2019-4fee-a5e9-279d91306f08.jpg)

**Comment by jgriffiths** [comment]
Hi,

The temperature spike in London caused a google data centre failure which is heavily impacting multiple hosted services including us, please see https://twitter.com/blockstreamhelp and https://status.cloud.google.com/

We hope to have things up and running ASAP, apologies for the inconvenience.

**Comment by screweduser** [comment]
720 days later, it worked.

**Comment by domegabri** [comment]
@screweduser please set up more than one 2FA, if possible. Remember that you can also use google authenticator and backup the authenticator secret, so that you can recover the 2FA on any device at a later date in case you lose access to your main 2FA device.
