### ISSUE TITLE
Feature request: Message signing

### ISSUE THREAD

**Issue by dspicher** [Blockstream/green_android#115]
### Description

I would like to be able to sign messages with a particular address, along the lines of https://github.com/bitcoin/bitcoin/blob/master/src/util/message.cpp#L56.

**Comment by alessandro-saglimbeni** [comment]
Hey this is already avaialble, for singlesig accounts https://help.blockstream.com/hc/en-us/articles/26127251627545

**Comment by dadofsambonzuki** [comment]
> Hey this is already avaialble, for singlesig accounts (not possible for multisig accounts, given that no standard for signing with those addresses exists, therefore, no service provider would be able to validate a signature from those addresses either)
> 
> See this guide if you want to knowhow to do this https://help.blockstream.com/hc/en-us/articles/26127251627545

Awesome, that is buried deep!
