### ISSUE TITLE
Can't recover my wallet in version 3.5.9

### ISSUE THREAD

**Issue by eliasspro** [Blockstream/green_android#117]
i installed the new update from playstore version 3.5.9, i open the app and it asks me to enter my pin, i usually use fingerprint biometric to login, i entered the wrong pin 3 times and i was asked to recover my wallet using mnemonic phrases
I have tried many many times but all i get is LOGIN FAILED error.

**Comment by domegabri** [comment]
Hi @eliasspro is this still an issue for you?

**Comment by angelix** [comment]
@eliasspro please reopen if issue still persists.

**Comment by eliasspro** [comment]
Thank a lot it's been solved
