### ISSUE TITLE
Remove android.enableJetifier line from gradle.properties

### ISSUE THREAD

**Issue by emanuelb** [Blockstream/green_android#118]
https://github.com/Blockstream/green_android/blob/68abba74099cf322e255681c7039e45a0b59fc6a/gradle.properties#L23-L24

see this guide for the steps to ensure it's safe to remove this lines (check that all deps are already fully migrated to AndroidX)
https://medium.com/dipien/say-bye-bye-to-android-jetifier-a7e0d388f5d6

**Comment by angelix** [comment]
Removed. Thanks for reporting.
