### ISSUE TITLE
Feature request: add an option to edit accounts

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#12]
Feature request: add an option to edit accounts.

**Comment by bitschmidty** [comment]
@bitcoinuser I assume you want to edit the name of the account? If not, let me know what you were looking to do.

**Comment by angelix** [comment]
@bitcoinuser @vindard feature is implemented.

**Comment by Alex71btc** [comment]
me too, every watchonly wallet on the market ( Bitbox, Trezor, Sparrow, Specter, Nunchuk) has this simple feature! except blockstream...they refuse to implement it, I will fork if they never  implement this, it is not praktical at all if you have a lot of subaccounts to not get mixed up without correct naming!
