### ISSUE TITLE
use git submodule instead of fetch_assets.sh

### ISSUE THREAD

**Issue by Giszmo** [Blockstream/green_android#121]
### Description

It's kind of unexpected that the compilation requires curl and jq and pulls stuff from `https://raw.githubusercontent.com` which doesn't get the same cryptographic checks a git revision could get. Why not add asset_registry_db as a git submodule instead?

**Comment by angelix** [comment]
@Giszmo `fetch_assets.sh` was removed and cached assets are provided by GDK.
