### ISSUE TITLE
Please tag 3.6.4

### ISSUE THREAD

**Issue by Giszmo** [Blockstream/green_android#124]
Trying to reproduce the latest release from Google Play Store (sha256sum 9a796e5b8986c727e0cd112899c40cdd832c94805aa9a547a7daf95ec5ec9dc5) I see 3 potential revisions to try. Please make clear which of those the app was compiled from.

**Comment by domegabri** [comment]
Hello, sorry for the late push of the tag. It has been published; see https://github.com/Blockstream/green_android/tree/release_3.6.4
