### ISSUE TITLE
Building Android Release in Docker Fails

### ISSUE THREAD

**Issue by GoofyAF** [Blockstream/green_android#127]
### Description

When attempting to build the android release in docker, whether manually building the container via the image in the contrib/ directory as described in BUILD.md or pulling the greenaddress/android image from docker hub, the build fails and an error is displayed.

### Version

release_3.7.3

### Steps to reproduce
```
git clone https://github.com/Blockstream/green_android.git
git checkout release_3.7.3
cd green_android/contrib/
docker build -t greenbits_docker .
cd ..
docker run -v $PWD:/gb greenbits_docker
```
OR
```
docker pull greenaddress/android && docker run -v $PWD:/gb greenaddress/android
```
### Expected behaviour

I expected an APK package of the latest release

### Actual behaviour

There are two issues I can identify:

1) the greenbits_docker image actually uses the /ga directory to copy and run the prepare_fdroid.sh script while the current instructions suggest binding the volume to /gb

2) The ANDROID_NDK parameter is not being set. 

In the BUILD.md instructions the only reference to this variable is:

```
You must set the environment variables `ANDROID_NDK` and `JAVA_HOME`
correctly, then run:
```

My assumption was that these variables would be handled in the Docker file.

### Screenshots
```
$ docker run -v $PWD:/ga greenbits_docker
dirname: missing operand
Try 'dirname --help' for more information.
./prepare_fdroid.sh: line 8: ANDROID_NDK: parameter null or not set


$ docker pull greenaddress/android && docker run -v $PWD:/ga greenaddress/android
Using default tag: latest
latest: Pulling from greenaddress/android
Digest: sha256:3dd3e673d8045e9af17bc5bf72585768da12d44b05e2e51aff00ae17229a595d
Status: Image is up to date for greenaddress/android:latest
docker.io/greenaddress/android:latest
dirname: missing operand
Try 'dirname --help' for more information.
./prepare_fdroid.sh: line 8: ANDROID_NDK: parameter null or not set
```

### Device or machine

lenovo x230 running popOS 21.04
Docker version 20.10.7, build 20.10.7-0ubuntu1~21.04.1

### Additional info

Attempting to build the 3.7.3 SDK due to the slower release cadence of Blockstream Green on FDroid and the current unuseability of any version below 3.7.3

**Comment by angelix** [comment]
@GoofyAF Build instructions are updated. Please reopen if you have any issue. Thank you.
