### ISSUE TITLE
PIN is difficult to type on large screens

### ISSUE THREAD

**Issue by nugel** [Blockstream/green_android#130]
### Description

PIN is difficult to type because the keys are stretched across the entire device screen

### Version

Android 3.7.6

### Steps to reproduce

1. obtain a larger phone (around 6,5" or more)
2. create a wallet
2. lock the wallet with a PIN
3. open the app while locked
4. type the PIN

### Expected behaviour

PIN can be written easily without stretching both thumbs on both sides of the device.
Keypad should be smaller.

### Actual behaviour

Number keys are positioned in such layout that keys are very far apart and it required additional effort to type the PIN with one hand. 

### Screenshots

![green376](https://user-images.githubusercontent.com/54183462/145070642-39134411-a10c-4e6a-a4da-7de7855e1e99.png)

### Device or machine

Google Pixel 6 Pro
Android 12, build 210817.036

**Comment by angelix** [comment]
Thanks @nugel for reporting. Fixed in 09ea3bb375e9daf4238b15465b15886419a94eab.
