### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [Blockstream/green_android#131]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 12  warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on green_android (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure). 

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve green_android's security, and the quality of the reports of static analysis tools.
(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by jgriffiths** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi @misterAnderson90,

Thank you very much for getting in touch and disclosing to us responsibly - we really appreciate it!

You can contact us securely via the instructions in https://github.com/ElementsProject/libwally-core/blob/master/SECURITY.md, either myself directly in the first instance, and/or the Blockstream security email security@blockstream.com.

You can verify the blockstream email address and pgp key above via the https://blockstream.com/contact/ page. We will acknowledge receipt of your findings and discuss with you a timeline to review and respond.

-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEE5syRf0Pzb8CbvMYE9xwiw9sfcicFAmG9Rn4ACgkQ9xwiw9sf
cicY2A/7BsOpomuCINuTolm9tufiuwq8JGCbVbrab8in04Omk0nRfr49Mm6ydY8n
UrrCZW8mWEcFWj8DZkaZdZKTi8ysAYYsAQWMcwDfdR21LNkJgchC5Qc7+F/d62Dr
R9iBU0oykPBtlhQIWpZs4IEE9fm03hbMPatXQ7kLfPjE44hpJo/y9G7T9WXypaeh
Zcdf6F69BHubnC+FqmnMcm9Y0OnzUM9bRCIPnvbw5vhCxabZJtWsu2t5Mj4sCgjJ
cBoTx7t9XsbXDBdL3LGoY7X1FLtsNxj7SVCWEp6WfyVfO2jOg4cGg4L1pFQVLyqk
Iq5Bu3YYt9/FVeQe5gyi/wkppIQ7JSm7MeU4i8/nNvHYVb7x7o2LJ9UN/Rio8pxi
dYrp2/nlFFm0095GrmejgNQpiD8Q3S6llmXnjQucs60LrVinWjg4uyqz7v+DjO/k
ntPP7xWzGQmORF+gTKyksbYrx9nANTGgCKTEcO0m44ckiQuCnBqajR/jsEsxPrsY
u+r3JOObXDu1AismoB40nDislRZ5lgARwsWgf2qRyb2hOsfOPv0jRbWGh8xlk46L
eC7RNlE26sLk8h87zWe9sjbfotGD/c5xTfsCaLzNHPXNXO0WZzV+2D7KcHpU+Oa4
5Xg0fYCvC9ChiOTExBsFOBDI7Bv5XdF/Yjkl3IQgj5qOJytF0To=
=41dr
-----END PGP SIGNATURE-----

**Comment by misterAnderson90** [comment]
Hi @jgriffiths,

I have sent the documented gists to security@blockstream.com.

Please let me know if you need to clarify anything.

**Comment by jgriffiths** [comment]
Thanks @misterAnderson90 !

I will close this issue and we should respond to you according to our security policy in due course.

**Comment by misterAnderson90** [comment]
Hello @jgriffiths,

Did you receive the warnings by email? If yes, could you please share with me your perceptions about the gists I have sent you?

**Comment by jgriffiths** [comment]
Hi @misterAnderson90 

I've asked the Android peeps again to respond to you, apologies it seems to have slipped off their radar.

**Comment by lvaccaro** [comment]
Hi @misterAnderson90 , thanks for the report and sorry to be late.
I replicated the CryptoAnalysis Summary with the develop version of [CogniCryptSAST](https://github.com/CROSSINGTUD/CryptoAnalysis) .

If I get the same reports, most of the errors are related to ORDER section , which will follow a specific MR to solve all these warnings. A more deep investigation will follow to complete others warnings.

Thanks for your contribution, I'd like to integrate codecrypt in the ci process, and other techniques to detect vulnerabilities. Open for feedbacks.
