### ISSUE TITLE
App crashes when trying to connect to Ledger Nano S

### ISSUE THREAD

**Issue by DokStook** [Blockstream/green_android#134]
### Description

App crashes when trying to connect with ledger device

### Version

3.7.7

### Steps to reproduce

Open app
Click add ledger device
Click on device
Crash

Note: the pin has been inputed and the bitcoin app open

### Expected behaviour

Add my ledger device

### Actual behaviour

App crash

### Additional info

If I knew how to get logs I would have pasted them here

**Comment by angelix** [comment]
@DokStook thanks for reporting. Can you also share your Android version?

**Comment by DokStook** [comment]
Android 12

**Comment by angelix** [comment]
@DokStook There is a fix in the upcoming release. Until then the only workaround is to select the Green app on the Android prompt when you connect the device.

**Comment by DokStook** [comment]
The problem is that I don't get prompted

**Comment by DokStook** [comment]
I have one more question. What is the approximate release date for the release?

**Comment by DokStook** [comment]
Hello, just boult the app on my own. Everything is now  fixed.

**Comment by jpph** [comment]
It is working when installing on the ledger nano s/x the app "bitcoin legacy" (you need to enable developper mode in ledger live desktop). It is prompted when using green desktop but not green on android. You might add a message for the android app also ?
