### ISSUE TITLE
Translations do not reflect the changes I did on Transifex site

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#136]
Hi @lvaccaro 

Why on version 3.7.9 I don't see all PT-BR translations I did on transifex?

This file doesn't reflect the translations of transifex: https://github.com/Blockstream/green_android/commit/f73ca27ad1ad5eafd21dc9bccb3f37981f924461

**Comment by lvaccaro** [comment]
Hi @bitcoinuser , sorry to hear about that. 
In https://github.com/Blockstream/green_android/commit/f73ca27ad1ad5eafd21dc9bccb3f37981f924461 strings was aligned at ~ 16 feb 2022 (same for green iOS), so some recent translations miss. 
I resync strings just now in b80ddf3304871bd133bb4a90cea2b5add7faad2d.

nit: some strings in PT-BR contains a zero-width space as (maybe it is pre-existing issue):
```
   <string name="id_assets_cannot_be_used_on_bitcoin">Ativos não podem ser usados <U+200B><U+200B>na rede Bitcoin</string>
...
+  <string name="id_blockstream_green_needs_access">A Blockstream Green precisa acessar o Bluetooth para se conectar a carteiras físicas. Os dados de localização não são usados <U+200B><U+200B>ou mantidos pela Blockstream.</string>
```

**Comment by bitcoinuser** [comment]
> A Blockstream Green precisa acessar o Bluetooth

Hi, thanks for the update. I didn't understand this comment:

nit: some strings in PT-BR contains a zero-width space as (I don't know if it is for formatting purpose):

For me is all good.

**Comment by bitcoinuser** [comment]
> I resync strings just now in [b80ddf3](https://github.com/Blockstream/green_android/commit/b80ddf3304871bd133bb4a90cea2b5add7faad2d).

In which Green version this will be applied?

**Comment by alessandro-saglimbeni** [comment]
In the next release 3.8.0

By the way, are these the translations you are expecting to see in the next release? (Make sure you click on `Load diff` if you're only seeing the Russian strings)
https://github.com/Blockstream/green_android/commit/b80ddf3304871bd133bb4a90cea2b5add7faad2d#diff-8e6cc67bc27f0d960375b3c26fd1d1a2305836f2a661801be1eaf5bc808921cd

**Comment by bitcoinuser** [comment]
> In the next release 3.8.0
> 
> By the way, are these the translations you are expecting to see in the next release? (Make sure you click on `Load diff` if you're only seeing the Russian strings) [b80ddf3#diff-8e6cc67bc27f0d960375b3c26fd1d1a2305836f2a661801be1eaf5bc808921cd](https://github.com/Blockstream/green_android/commit/b80ddf3304871bd133bb4a90cea2b5add7faad2d#diff-8e6cc67bc27f0d960375b3c26fd1d1a2305836f2a661801be1eaf5bc808921cd)

Yes I expect to see on next release. Yes, I clicked on load diff and I see the changes on Pt-br. Thanks, I will wait the next release. Hope soon. Thanks.
