### ISSUE TITLE
Recommend&Support newer supported NDK version

### ISSUE THREAD

**Issue by emanuelb** [Blockstream/green_android#138]
From BUILD.md
https://github.com/Blockstream/green_android/blob/1dd01922c87e417d6c31cd2c34864bd0fc1ef37c/BUILD.md#L37
https://github.com/Blockstream/green_android/blob/1dd01922c87e417d6c31cd2c34864bd0fc1ef37c/BUILD.md#L49

The recommended version is 19b which is very old, list of supported ndk versions are:
Latest LTS Version: r23b
Latest: r24
https://developer.android.google.cn/ndk/downloads?hl=en

**Comment by angelix** [comment]
Fixed in cd612f83c7f2e61cda9c432d1f7fb69ddb100b1f
Thanks for reporting
