### ISSUE TITLE
Feature Request: Verify receive address on hardware wallet

### ISSUE THREAD

**Issue by davidlick** [Blockstream/green_android#139]
### Description

Receive addresses are generated on the android device and are not verified on hardware wallets. Tested on Ledger Nano X only but the documentation seems to indicate that Green doesn't implement this for any other hardware wallets.

This step is critical to ensure that the mobile device has not been compromised and that the receive address is indeed derived from the private key. Without this feature I cannot use this app for day to day transactions as I can't have any confidence that I'm receiving funds to a wallet I control.

### Version

v3.8.0

### Steps to reproduce

Connect Ledger Nano X and click "Receive"

### Expected behaviour

An address is displayed on screen with a dialogue indicating the user should check the generated address against the one displayed on their hardware wallet device.

### Actual behaviour

An address is displayed with no verification.

### Screenshots

None taken, but please let me know if they're required.

### Device or machine

Hardware wallet: Ledger Nano X
Mobile: Pixel 6Pro running CalyxOS

### Additional info

Ledger's bitcoin app has a command to GET_WALLET_ADDRESS documented here: https://github.com/LedgerHQ/app-bitcoin-new/blob/develop/doc/bitcoin.md#get_wallet_address

**Comment by alessandro-saglimbeni** [comment]
Hi @davidlick thanks for the report, this will be added on the next release

**Comment by davidlick** [comment]
@alessandro-saglimbeni Just got the release with this new feature and it works flawlessly. Thank you!

**Comment by alessandro-saglimbeni** [comment]
@davidlick we don't, but the team thanks you for your generosity :)
