### ISSUE TITLE
You are not connected to the internet...

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#14]
On version 3.0.7 I still see the (You are not connected to the internet) 
Obs. My connection is ok

![photo4947367906686118008](https://user-images.githubusercontent.com/1178856/54848912-55006880-4cc1-11e9-9b32-f7c0bdaf209c.jpg)

**Comment by bitcoinuser** [comment]
To connect, I need to kill Green and open it again and login.

**Comment by alessandro-saglimbeni** [comment]
We are working on a fix for this issue, we will update this issue as soon as it is out.

**Comment by domegabri** [comment]
any improvement using 3.0.8? Does this happen to you every single time?

**Comment by bitcoinuser** [comment]
I uninstalled Orbot and now looks like everything is ok. I don't know if Orbot was the reason to this problem.

**Comment by bitcoinuser** [comment]
Looks like it's fixed. If I see reproduce the problem again, I reopen it. Thanks.

**Comment by nharmon9** [comment]
I get this when I try to connect to regtest using Android Studio
