### ISSUE TITLE
Transactions can appear out of order if they are mined in the same block

### ISSUE THREAD

**Issue by kaiwolfram** [Blockstream/green_android#141]
### Description

When transactions have been mined in the same block they sometimes appear out of order in the transaction overview list.
It becomes apparent when the seemingly first transaction (the one on the bottom) spends sats that haven't been available yet (see screenshot below).

### Version

3.8.2 release and also latest commit in master e853833ce78ee50664d7f8ed7afd19360651a661

### Steps to reproduce

Receive and send a transaction in the same block. You can reproduce the wallet in the screenshot with `abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about` -> Segwit account 2

### Expected behaviour

Transactions that are mined in the same block should appear in a logical order, i.e. receiving sats before sending them

### Actual behaviour

They sometimes appear out of order like the two txs on the bottom of the screenshot

### Screenshots

![image](https://user-images.githubusercontent.com/48265657/170823560-f4f39d4a-92c9-43cb-bcfe-2644f66b8607.png)

### Device or machine

Nokia 5 on Android 9, Ubuntu 21.10

**Comment by domegabri** [comment]
the app doesn't reorder transactions but shows them as they are returned by gdk

**Comment by jgriffiths** [comment]
@kaiwolfram Thanks for reporting. Please raise this issue under https://github.com/Blockstream/gdk/ - We already have an internal issue tracking this for singlesig accounts, but a public issue would also be good perhaps.
