### ISSUE TITLE
Feature request: Pasting QR code from image

### ISSUE THREAD

**Issue by slush0** [Blockstream/green_android#153]
### Description

Currently it is not possible to use QR code, which is displayed directly on the phone screen. 

### Expected behaviour

Please allow reading QR code from local file AND/OR allow pasting pictures from clipboard containing QR code. Thanks to that, it would be easy to screenshot QR code and simply paste it to "Receiver address" in Send dialog.

### Actual behaviour

QR code can be scanned only by using phone's camera. This is not practical when you have the payment request directly on the phone screen.

**Comment by angelix** [comment]
@slush0 soon to be implemented.

**Comment by angelix** [comment]
Implemented in d1838b5016f46bcb204825e8feea956cb62e378c, soon in 4.0.11
