### ISSUE TITLE
Add CZK/BTC currency pair

### ISSUE THREAD

**Issue by slush0** [Blockstream/green_android#154]
### Description

The application cannot handle CZK (Czech Koruna). Bitcoin is widespread in Czechia and Green not supporting CZK is major blocker in using this otherwise great wallet here.

### Expected behaviour

The application can natively work with CZK (both in entering values in Send dialog and displaying amounts in CZK in transaction details).

This can be implemented by pulling CZK/BTC rate from some Czech exchange (for example coinmate.io is respected player with CZK rate and good API) or by converting the rate indirectly from EUR/BTC and EUR/CZK rates.

Coingecko API also includes BTC/CZK as many as miriad of other national currencies.

### Actual behaviour

No support for CZK.

**Comment by jgriffiths** [comment]
Hi @slush0 I've added support for Czech koruna (via coingecko) to the multisig backend, this should be rolled out to the testnets shortly and then mainnets with the next scheduled updates.

The apps will pick up the new rate automatically and it will then become available in settings.

Note that the FX rates impl for singlesig is currently being switched to a new feed, once that is tested and stable I imagine we will open up other ccy pairs to match those available on the backend currently.

Thanks for the report!

**Comment by jgriffiths** [comment]
@slush0 CZK is now available for your testing on the BTC and Liquid testnet backends, please let us know if you encounter any issues. This should be rolled out to the mainnet backends within a couple of weeks as part of our next update, thanks.

**Comment by slush0** [comment]
Thank you for swift response and implementation!

However, I tried to test it and I don't see any exchange rates in singlesig testnet account except of "USD". As there aren't any other rates either I suppose it is non releavant issue, but just FYI.

**Comment by jgriffiths** [comment]
@slush0 yes unfortunately singlesig at present does not offer the full suite of rates available in multisig; we are working to provide the full set or pairs to singlesig and hope to have that available in the near future.
