### ISSUE TITLE
Don't wait on user to press OK post mnemonic qrcode scanning

### ISSUE THREAD

**Issue by greenaddress** [Blockstream/green_android#16]
### Description

When scanning (24 words) mnemonic it shouldn't wait for me to press OK to go to PIN.
For 27 it should ask for password and then go straight to PIN.

### Version

both 3.0.6 and 3.0.7

### Steps to reproduce

Scan mnemonic. You will have to press ok to continue.

### Expected behaviour

Scan mnemonic. You won't need to press ok to continue to the next step (PIN)

**Comment by domegabri** [comment]
2fb3e46813f50629f67c55b294536f28f2365bcd
