### ISSUE TITLE
Reproducibility problem with v4.0.1

### ISSUE THREAD

**Issue by mohammadrafigh** [Blockstream/green_android#169]
### Description

Tried to reproduce the latest release (v4.0.1) but got a diff in `/assets/dexopt/baseline.profm`. This may be related to [this](https://issuetracker.google.com/issues/231837768?pli=1) AGP bug which could be fixed easily by upgrading AGP.

### Version

v4.0.1

**Comment by angelix** [comment]
@mohammadrafigh AGP was updated to `8.1.2`.
If the issue persist, please re-open the issue.
Thank you for reporting.

**Comment by Giszmo** [comment]
I just built the latest version 4.0.22 and it had a diff in baseline.prof but also in other parts.
