### ISSUE TITLE
Creating Watch-Only wallet single sig not possible

### ISSUE THREAD

**Issue by Funman2** [Blockstream/green_android#170]
### Description

setting up a watch only wallet in blockstream green android does not work for me, after entering the zpub, there is no way  or button to save the wallet

### Version

4.04.

### Steps to reproduce

try ti set up watch only sngle sig

### Device or machine
android 9 phone

**Comment by Funman2** [comment]
Resolved the issue by reducing the font size of my Samsung Galaxy S8 phone. 
Then I could see the login button for watch only wallets.

**Comment by angelix** [comment]
Fixed in e3be853e9f746b9545b88667f5e107ae98960571.
It will be available in the next release `4.0.5`.
Thanks for reporting.

**Comment by Funman2** [comment]
Thanks!
