### ISSUE TITLE
Importing watch only not possible

### ISSUE THREAD

**Issue by f321x** [Blockstream/green_android#171]
### Description

In the paste xpub screen it's not possible to scroll down to see the save button. So it's not possible to create the wallet.

### Version

Newest on play store (13.05.)

### Steps to reproduce

Download wallet, accept telemetry, try to import zpub

### Screenshots

![IMG-20230513-WA0004](https://github.com/Blockstream/green_android/assets/51097237/ec78c1c5-c93f-4dab-8847-9b2a76cdf275)

### Device or machine

Xiaomi Mi A3 android 11

**Comment by angelix** [comment]
Fixed in https://github.com/Blockstream/green_android/commit/e3be853e9f746b9545b88667f5e107ae98960571.
It will be available in the next release 4.0.5.
Thanks for reporting.
