### ISSUE TITLE
Crash on wallet recovery

### ISSUE THREAD

**Issue by f321x** [Blockstream/green_android#176]
### Description

When doing wallet recovery and entering seed words the app randomly crashes and I have to start again. I quickly switched between app while entering the seed words (typing words from another app). Took 4 tries to successfully enter all 12 words.

### Version

4.0.4

### Steps to reproduce

Recover wallet, enter some words, switch to other app, switch back, try to enter another word (don't know if the multitasking is the reason though)

### Expected behaviour

Not to crash

### Actual behaviour

Crash

### Device or machine

Pixel 6a, GrapheneOS, Android 13, Sandboxed play services

**Comment by domegabri** [comment]
We can't reproduce this in the latest release. Let us know if this is fixed for you too. Please reopen this bug in case you still have troubles.
