### ISSUE TITLE
BTC: cannot send BTC or mBTC only satoshis (i18n mixes up the ',' and '.') 

### ISSUE THREAD

**Issue by eckelj** [Blockstream/green_android#179]
### Description

I received satoshis on my address https://blockstream.info/address/bc1qk7ez5avdn4twauccmkl5k5gjhehz52cl0mezfn
and want to send a fraction of it to a service. 

Unfortunately, I cannot press the sending button in the application when I try to send BTC or mBTC, only the denomination of Satoshi works after trying around for a while.

### Version

4.0.18

### Steps to reproduce

1. connect jade wallet
2. enter pin
3. enter passphrase
4. select BTC account
5. Scan or enter the recipient address to send funds to
6. select a value below 0.02909348 (on my green wallet, this is shown with a ','), e.g. 0.01

The display shows now that I don't have enough funds. Even though I have (it's listing them)
If I select to send the complete amount of BTC that I have, e.g. 0.02909348, it allows me to send this. 
Typing the maximum amount myself won't let me send the amount either. 

7. I found out that switching to Satoshi works for me. 
8. that's because there aren't any ',' or '.' to separate the decimals or the other positions. 
9. therefore, I assume the issue is about '' and '.' differences. I am not able to use a '.'. Pressing ',' or '.' results in ',' being put on the screen. 

### Expected behaviour

I expect to get a '.' or ',' when I press the corresponding buttons. the i18n of the app seems to mix that up. 

### Actual behaviour

1. pressing ',' results in ','
2. pressing '.' results in ','

therewith I am not able to write a transaction value except for in the denomination of Satoshis (which is a workaround that I found at one point).

### Device or machine

Android phone

**Comment by angelix** [comment]
@eckelj Fixed in 877a185f98b3d934455ed87bcec5cb1f990eb79b, soon to be released in Google Play.
Thank you for reporting the issue.

**Comment by eckelj** [comment]
Thank you. Looking forward!
