### ISSUE TITLE
Items of setting page should appear collapsed

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#18]
Items of setting page should appear collapsed:

NETWORK
ACCOUNT
TWO-FACTOR
SECURITY
ADVANCED
ABOUT

**Comment by bitcoinuser** [comment]
Example:

![photo4958880450558928944](https://user-images.githubusercontent.com/1178856/55012183-c55f0080-4fc5-11e9-915a-41e596e01bcd.jpg)

**Comment by alessandro-saglimbeni** [comment]
Thank you for this suggestion, we took not of it.
