### ISSUE TITLE
Terms and policies are not accessible via Tor

### ISSUE THREAD

**Issue by licaon-kter** [Blockstream/green_android#182]
```
Error: Forbidden
Your client does not have permission to get URL /green/privacy/ from this server
```

**Comment by domegabri** [comment]
Hello @licaon-kter , this is not a bug in Green but in the blockstream website. I have passed this along to the maintainers.

**Comment by nitramiz** [comment]
@licaon-kter This happens somewhat frequently when visiting sites over Tor. You can recreate the Tor circuit from your browser to the server by clicking the button before the URL.
https://support.torproject.org/glossary/new-tor-circuit-for-this-site/
![Screenshot from 2024-01-17 12-28-33](https://github.com/Blockstream/green_android/assets/16788093/84b947f5-c12c-4ff8-89b6-9b11c8e779b2)

**Comment by licaon-kter** [comment]
It means that some exit nodes are blocked, right?
