### ISSUE TITLE
Bug in app

### ISSUE THREAD

**Issue by Rothschildiuk** [Blockstream/green_android#183]
### Description

After pressing the right button on my "SegWit Account 1", I am thrown out of the application. I continue to see a notification about the connected device (screenshot 2), but when I open the application again, I see start app screen and I need, enter the pin code and Passphrase again.

### Version

Green 4.0.21
Jade 1.0.26

### Steps to reproduce

Login with Jade then just click on button arrow right (see screenshot)

### Expected behaviour

open wallet

### Actual behaviour

go out from app

### Screenshots

![photo_2023-12-12 01 48 26](https://github.com/Blockstream/green_android/assets/15833131/efee29c5-d9e6-42f2-aa84-ab742c75fcd7)
![photo_2023-12-12 01 57 40](https://github.com/Blockstream/green_android/assets/15833131/36f0c882-78d3-4f7b-9e09-8e5da8d8c291)

### Device or machine

Google Pixel 8 Pro (android 14)

**Comment by Rothschildiuk** [comment]
The same happens with my Liquid wallet.

**Comment by angelix** [comment]
Thank you @Rothschildiuk for reporting.
We have identified the issue and soon we will release a fix.

**Comment by angelix** [comment]
Fixed in 75d23e2cc313a249d91ee36d1678e80dde5448d9
