### ISSUE TITLE
Sweeping of funds after closing of a lightning-channel fails

### ISSUE THREAD

**Issue by zyklopisch** [Blockstream/green_android#185]
### Description

After the Lightning-channel was force closed automatically and when I now want to Sweep the BTC to get it back on-chain, it everytime throws this error messages. I tried about 30x times throughout a month, it is everytime the same. Tried with and without TOR-connection.

### Version

4.0.21

### Screenshots

![3](https://github.com/Blockstream/green_android/assets/101331130/6cd4a310-158e-4b50-a072-55e324815d2d)
![2](https://github.com/Blockstream/green_android/assets/101331130/d48291b3-5150-4cf0-881a-3920091a395c)
![1](https://github.com/Blockstream/green_android/assets/101331130/1e05147f-050e-4b72-8640-6d42a053d1b4)

### Device or machine

Android Phone, latest

**Comment by SergeyShirin** [comment]
Problem still persists in 4.0.24.
![Screenshot_20240216-101423](https://github.com/Blockstream/green_android/assets/57345478/9595db08-ba68-4f9e-8e0c-14868c50251b)

**Comment by angelix** [comment]
Hi @SergeyShirin @zyklopisch 

To better understand what's going on with your node and to try to fix the issue, please export your Lightning account logs. 

To do this follow the steps:
1. Login into your wallet
2. Navigate inside your lightning account
3. From the top-right menu, click on "Node Info".
4. Click on "Share Logs"
5. Download the logs and attach them to a support ticket.

Please use the official [support form](https://help.blockstream.com/hc/en-us/requests/new?ticket_form_id=8613) to share the logs.

DO NOT share the logs in this public issue.

Thank you.

**Comment by SergeyShirin** [comment]
> Hi @SergeyShirin @zyklopisch
> 
> To better understand what's going on with your node and to try to fix the issue, please export your Lightning account logs.
> Please use the official [support form](https://help.blockstream.com/hc/en-us/requests/new?ticket_form_id=8613) to share the logs.

I have attached the logs to my support ticket #35901.

**Comment by angelix** [comment]
@SergeyShirin 
We are looking into your logs. I have some questions.
- How many wallets do you have in your app?
- How many LN accounts do you have in the app? 

Thanks

**Comment by SergeyShirin** [comment]
@angelix ,

In the app instance from which I sent the logs, I have one wallet and one LN account in it. At the moment when the channel was force-closed, the LN account was the only account in the app. Later, right after the closure of the channel, I also opened Legacy Segwit account, Standard account, 2FA Protected account and 2of3 with 2FA account. All of them are within the same wallet.

Then, a couple of days later, I also installed the app on another device and restored the wallet from the seed phrase there. So, on another device, I have two wallets in the app, and only one LN account which is within the restored wallet.

Interesting fact. Two different instances of the app (on two different devices) show different txid for the transaction which closes the channel. The second device (where the wallet was restored from the seed phrase) shows correct txid. The first (initial) device shows the txid which doesn’t exist in the blockchain.

Do you need my logs from the second device?

**Comment by angelix** [comment]
> Do you need my logs from the second device?

@SergeyShirin Sure, that would be helpful

**Comment by SergeyShirin** [comment]
@angelix ,
I’ve sent them in the ticket.

**Comment by zyklopisch** [comment]
Problem still persists in 4.0.25

**Comment by zyklopisch** [comment]
Today I tried again and it worked! Seems fixed!
