### ISSUE TITLE
Can't change fiat currency, rename of wallets fail

### ISSUE THREAD

**Issue by Funman2** [Blockstream/green_android#186]
### Description

In newest Android version,  the rename of wallets fails,  just no change after entering. Also when trying to change Fiat denomination to EUR it says I have to be logged in, although already logged in for watch only account. 

### Version

4.0.22 and also tried beta, same result. 

### Steps to reproduce

Install green on samsung galaxy S21 FE

### Expected behaviour

It used to work in older versions of green. 

Samsung Galaxy S21 Fe smartphone,  Android 14, One Ui 6.0

**Comment by Funman2** [comment]
![Screenshot_20231227_113120_Green](https://github.com/Blockstream/green_android/assets/105175715/d05c50f5-1935-4345-842f-10f55ea0407e)

**Comment by Funman2** [comment]
I tried all prior versions, all had the same bug, but when I went back to green android 4.0.18 it worked again,  no bug. Fiat EUR working and wallet rename as well. 
So will stay on this release until fix.

**Comment by Marc-Gee** [comment]
4.0.22 
Piexl 7:
Account renaming did not work: The rename does display initially, but then is not shown after coming back into the app. 
Its very unintuitive how the pop-up menu displays.

The renaming of a wallet should not be only on the home screen (i found it eventually) . When a user only has 1 wallet, it seems impossible to rename the wallet. That should be editable on the wallet screen also please.

**Comment by domegabri** [comment]
We have temporarely disabled editing account names and preferences for watch-only in version 4.0.23 until a bug in the library gets fixed.

**Comment by Funman2** [comment]
Ok😵‍💫

**Comment by angelix** [comment]
> Ok😵‍💫

This is not exactly a library bug, but rather a current limitation that will soon be addressed by adding new synchronization capabilities between devices.
