### ISSUE TITLE
Feedback screen should be modal.

### ISSUE THREAD

**Issue by Marc-Gee** [Blockstream/green_android#187]
### Description

When entering feedback in the app's feedback text box "Give us your feedback" , tapping anywhere else on the screen loses the textbox and thus whatever was already typed in. 
Thats very frustrating. 
### Version

4.0.22

### Steps to reproduce
type some feed back into the feedback box, and then tap just outside of it. the feedback box is hidden and the contents are lost. 

### Expected behaviour
the user should explicitly choose a close or cancel dialog to lose their typed feedback,  before simply losing it. 
you will of course want to collect user feedback reliably. 

### Actual behaviour
the feedback windo just closes, and the their typed feedback is lost. 

### Device or machine
Pixel 7
Android 13

**Comment by angelix** [comment]
@Marc-Gee thank you for your suggestion. We 'll look into it.

**Comment by angelix** [comment]
Fixed in 8511d1ae496470f96b6b6105ddeca015bdd3aa9b
cc @Marc-Gee
