### ISSUE TITLE
The play store name should include Blockstream 

### ISSUE THREAD

**Issue by Marc-Gee** [Blockstream/green_android#188]
The google play store app name or details does not include "Blockstream Inc" anywhere. its instead published by "GreenAddress IT Ltd"

### Version

all versions

### Steps to reproduce
none. 

### Expected behaviour
"Blockstream Inc"  or similar should be the publisher name to help improve app authenticity.

### Actual behaviour
It has an unknown publisher. 

### Screenshots
![image](https://github.com/Blockstream/green_android/assets/91296549/82fd7e06-0912-4d52-bf3a-9a6ad6f03537)

### Device or machine
All android devices

### Additional info
In trying to find the authentic app, from the thousands of fake ones, User must at least see blockstream, and the other apps that Blockstream publishes, to establish that it is the authentic app.

**Comment by Marc-Gee** [comment]
Re-upping this issue, I believe that spammers will fake the wallet without some basic authenticity check.

**Comment by alessandro-saglimbeni** [comment]
Hi this is fixed now on Play Store
