### ISSUE TITLE
Green login use android standard. Should use a custom solution.

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#19]
When I login on Green I see this: 

![photo4952166957113780232](https://user-images.githubusercontent.com/1178856/54871219-847da680-4d8f-11e9-8c86-2b034b4788de.jpg)

Should use a custom solution like what conio.com wallet app does:

![photo4949735442983528581](https://user-images.githubusercontent.com/1178856/54871227-9d865780-4d8f-11e9-84f9-c1eaa74484d4.jpg)

**Comment by bitcoinuser** [comment]
Obs. When Green is minimized and "opened" again, should always ask for fingerprint or pin.

**Comment by angelix** [comment]
@bitcoinuser please reopen if current implementation needs improvements.
