### ISSUE TITLE
Bug: In watch-only wallets "Denomination & Exchangerate setting" not changeable

### ISSUE THREAD

**Issue by smartsourcefreak** [Blockstream/green_android#191]
### Description

When loading a wallet being "watch-only" there is an error message (authentication failure) when trying to change "Denomination & Exchange Rate" setting, letting me not change anything there.

### Version

4.0.21

### Steps to reproduce

Setup a new watch only wallet. Go into settings and try to change the settings for "Denomination & Exchange Rate"

### Expected behaviour

Let's me change to desired setting after I click "OK" - without any "authentication" at all.

### Actual behaviour

Error message "Authentication required". "OK" takes me back to the settings page without any change.

**Comment by domegabri** [comment]
we have temporarely disabled changing denomination and exchange rate in watch-only in release 4.0.23; we will re-enable this when the GDK bug is fixed.
