### ISSUE TITLE
Message signing not working for Liquid Addresses

### ISSUE THREAD

**Issue by Czino** [Blockstream/green_android#192]
### Description

Message signing is often required when buying Bitcoin within the EU. I found that it works for bitcoin addresses, however, when choosing a liquid address, nothing happens when clicking on `Sign Message`

### Version

`4.0.22`

### Steps to reproduce

1. click `Receive`
2. select Liquid Bitcoin
3. click `More Options`
4. click `List of Addresses`
5. click on sign icon for an address
6. type any message to be signed
7. click `Sign Message`
8. 
### Expected behaviour

Signature is presented

### Actual behaviour

Literally nothing happens, no feedback, no error message.

### Screenshots

![image](https://github.com/Blockstream/green_android/assets/42438775/b9589dd8-408c-4363-bf38-a52d1a57f3fb)

### Device or machine

Android 11

**Comment by domegabri** [comment]
this is a bug in the UI: signing addresses in liquid is not supported

**Comment by Czino** [comment]
I agree that it should not be accessible if not supported.

But I would also like to suggest to add [BIP322](https://github.com/bitcoin/bips/blob/master/bip-0322.mediawiki) support.
