### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#2]
Hi,

I was able to login, but now when I try to login I see this on Android:

![photo4940681613268854823](https://user-images.githubusercontent.com/1178856/54683283-094a9500-4af0-11e9-823b-9cdf185d9c25.jpg)

**Comment by greenaddress** [comment]
We are investigating it. Does it still happen if you force stop the app and retry?

**Comment by bitcoinuser** [comment]
No. This happened only one time when I tried to login with fingerprint. I restarted the app and now I can login with fingerprint or pin.

**Comment by friendsofbitcoin** [comment]
Tons of connectivity issues. Just tried to create and restore a 2nd wallet and it failed in android. Tried restoring wallet twice after rebooting android phone and the wallet accepts the 24 words but than crashes. Some attempts with logging on first wallet with pin just stalls. Is the server being overloaded? Will using my own full node with this wallet allow the user to not require communicating with Blockstreams server?

**Comment by bitcoinuser** [comment]
Another error that I usually see is this:
(Obs: my connection is ok)

![photo4947441281907402802](https://user-images.githubusercontent.com/1178856/54838896-786ae980-4ca8-11e9-9c7d-e73847b4b4cd.jpg)

**Comment by bitcoinuser** [comment]
Closing because I opened this issue: https://github.com/Blockstream/green_android/issues/14
