### ISSUE TITLE
Wrong amount calculation when receiving

### ISSUE THREAD

**Issue by f321x** [Blockstream/green_android#200]
### Description

When generating a receive address for L-BTC and specifying an amount the calculated reference value is completely wrong. When entering 1 € it shows 100m sats for example. See screenshots.

### Version

4.0.27

### Steps to reproduce

Generate L-BTC receive address, set amount.

### Expected behaviour

Show the correct reference value in Fiat or Sats

### Actual behaviour

Calculation is off

### Screenshots

![Screenshot_20240414-165847_1](https://github.com/Blockstream/green_android/assets/51097237/4553bd79-8b99-4323-a651-b09d5f03aa8e)
![Screenshot_20240414-165856_1](https://github.com/Blockstream/green_android/assets/51097237/0e8c55da-b176-4372-8d51-2565a9c82971)

### Device or machine

Google Pixel 6a GrapheneOS Android 14

**Comment by angelix** [comment]
Fixed in 4940d1ed202e84d1f91677b806f2d0c34c8cef48.
Thanks for reporting.
