### ISSUE TITLE
Connection to fulcrum server (clearnet) unreliable

### ISSUE THREAD

**Issue by f321x** [Blockstream/green_android#203]
### Description

I host a [Fulcrum](https://github.com/cculianu/Fulcrum) (electrum protocol) server on clearnet. On Sparrow and Bluewallet it works flawlessly and extremely fast. On Green it most of the time does not connect properly. Sometimes i can see new tcp client in the fulcrum logs, sometimes not. Sometimes Green loads the wallet, sometimes it shows "could not reach personal electrum server".
The server uses a self signed SSL certificate. I could imagine that there is maybe a compatibility problem between Green and Fulcrum? The connection was stable and fast so i rule out a connection error.
See the Fulcrum server url attached below.

### Version
4.0.28

### Steps to reproduce

Add my fulcrum server as personal electrum server. Open Wallet. See it loading very long, then either working or failing.

### Expected behaviour

The server and internet connection is reasonably fast. It works reasonably fast on Sparrow and Blue wallet, so in theory it should work fine with Green too.

### Device or machine

Google Pixel 6a GrapheneOS Android 14

### Additional info

Please find the URL of my Fulcrum server below, encrypted to your GreenAddress Team PGP. You can use it for testing.

-----BEGIN PGP MESSAGE-----

hQGMAzKHnG58ooovAQv/cwqcmoFIMX1AMuHGRCNRnQgHdwzur7q2EcTbidjvtLd3
pfucpdMCi7jK4JUqgAdhp0ocrnL9KVKpxpNRTEijo/6PG2+hgKKGgiNbv4WOQBjl
Mv/MQFLKCusu1C4HurBtKrbHgWAaxWDYVfGlVoD4xJeOJl/HxWRnETM484JDGX71
Oblm3HOMVtdLFb5w7J2EGMjlzRjAU0o3Ylq1TSyG3YFKkSFSBRlMT9as2SNbkxvS
mvQGLHPB+qVbwwJCrTryiWlAfMmk2kzqTbU+VSsedsjZkWdWF96Q6O2YVrSO/rCp
k9vIyf6Onpb2gAKRhEqo06alYOO3Cb0ozVM+geG7a2EV1sD9onKmm9iUSzj8A1AK
CIvrHw7OvaBkuebHPDCiS3q4uULUreMJmEOTp2JZ5NSbaPUT93v7hEntqz7shFnX
sdaeIJJvtTMqBr/sRNyHi1bNqHvSlrReKlL5g7aRMrbHN9wlqEbRbD5hLKGyEcJU
khquOwOqcbsymbklb6iChQIMA/Zl9qzf4PAaAQ//fh2rDI/gtSv9Pu3owV3SNE01
TijcU/XHFRdhcvTAtXnNfR65oaO9moQXKZjzNAsmYMDEnGGyjQtYj7yv025Ur8gF
p7vB3hJMgqMlIDdCz4z+FT7tT3LOj6mRIeVNhX8QWGtAX51AYfjr7rWACjkLv6E+
mSlpqE3fMzopFGGYT2V8e7IIEqu4ivpYYPtz7fdZ916LRReWzX8twKFqOLVJehRI
2mBfhe6VTiQ4GWjbJKLDkQMd91EKa2vkqi1FN//rW3nabMAEnIe15/6quY57Ttw2
0IGc7o7Ub7ehgm9IxBOMGYl+F7g6FL6DjzGGcrxzCjL8Q5Gg0xg8NyCTf/Y+Luf2
XDIjG5wFtXNEKQSv7+/rk08lxXIvFIbVpD1Xql6B+d3H8eVa665NL8pOI+xQTgRo
ftE61kg2k3GPv6uohskjeabPrHq4Mew0DKbKpWcTt3B3op9ujguYI+yb8viKViXQ
X5/XpZ+EVMaCuvbdcycgoaH5/Rz5hxd5u1snroQpnG/HjsnPqz8JpGWYfzjSeoAl
+TPV/wgxsfju/aipQ2OjOgdpN2nwGTDk5fprK1dJA26cjWYUUJvWOr0F7foavVID
FA55Rfk0e8OO3koIsREYW7cKgwWwpJl5oklkJNpws8v7n2A/EeFQ2vZpH+0Awgvj
+iQLok2oism9EQZvwdzSkQHK7YiFUA33OtV8ms/kaiDLDLdcnRpx3KRWR9sv9yN1
oYKyi5U6oKIeyCJsINTK2hRIVqdOT6fmjOSGIGCs4BoLVIu1g/B1snXvNA3s19wA
GJw3Pp6R82tlT5uIV1tUhe1TJcIoQgjJ6uRUSC1FkyGb6mhbMT6UUQDQ95wzuhp1
IH+/AWTiFKj+bkEpVau4zHE=
=dbzX
-----END PGP MESSAGE-----

**Comment by angelix** [comment]
@f321x Please check latest version, new settings give you the ability to disable TLS.

**Comment by f321x** [comment]
@angelix now it works, with TLS enabled. With TLS disabled i get "id_your_personal_electrum_server_for_s|Bitcoin" as pop up. But i expose my fulcrum server over SSL, so TLS should be enabled i guess
