### ISSUE TITLE
Address reuse after sweep

### ISSUE THREAD

**Issue by stevenroose** [Blockstream/green_android#205]
### Description

I recently swept my entire wallet, emptying it. (Not sure this is relevant, but might be) Then some days later i asked for a new receive address and it gave me an address that was used a month earlier. So it caused me to reuse my address. Doing so it also linked my swept funds to the newly incoming funds.

### Version

v4.0.28

### Steps to reproduce

see description

### Expected behaviour

always an unused receive address

### Actual behaviour

same address given twice

### Screenshots

n/a

### Device or machine

Android (F-droid build)

**Comment by angelix** [comment]
Fixed in https://github.com/Blockstream/gdk/commit/fa813d4c511046bb8bb0ebeba79253fa673ec3cd
Release 4.0.30 includes the fix.
Thanks for reporting.
