### ISSUE TITLE
App won't start after update to F-Droid version 4.0.28

### ISSUE THREAD

**Issue by xmready** [Blockstream/green_android#206]
### Description
App will not start after recent update to F-Droid version 4.0.28. The screen hangs on a black screen or the Green logo indefinitely.

### Version
Green version 4.0.28

### Steps to reproduce
1. Install version 4.0.28 from F-Droid
2. Open App

### Expected behaviour
I expect the app to open and work

### Actual behaviour
The app hangs on a black screen or the logo indefinitely.

### Device or machine
Pixel 7 Pro 
Android 14
GrapheneOS

### Steps taken
- Restarted phone
- Uninstalled Green, restarted phone, and reinstalled Green

**Comment by angelix** [comment]
Thanks for reporting this @xmready 

Unfortunately i wasn't able to reproduce your issue with my Pixel 7 Pro (stock firmware), so i guess it may relates to GrapheneOS.

I'll test again with GrapheneOS.

**Comment by iamnumbersix** [comment]
This F-Droid version 4.0.28 also crashes on Android 7.1.1. and Android 13

**Comment by angelix** [comment]
We identified the issue and working on a fix.
Relates to this [issue](https://github.com/jitpack/jitpack.io/issues/5752)

**Comment by angelix** [comment]
Fixed in a5fe83e903f580007dc5ec5316fa143be91aa6db, waiting F-Droid to build and release.
See discussion https://github.com/Blockstream/green_android/issues/173#issuecomment-2133290082

**Comment by angelix** [comment]
@licaon-kter 4.0.29 is still unpublished. Can you trigger the build process manually? 
Thanks

**Comment by licaon-kter** [comment]
It will be built this cycle: https://monitor.f-droid.org/builds/running

**Comment by angelix** [comment]
I can confirm latest version works fine.
Thanks you @licaon-kter for your help and @xmready for reporting.
