### ISSUE TITLE
com.android.installreferrer is not FOSS

### ISSUE THREAD

**Issue by licaon-kter** [Blockstream/green_android#217]
ref: https://github.com/Blockstream/green_android/blob/release_4.0.30/gradle/libs.versions.toml#L113

ref: https://github.com/Blockstream/green_android/commit/0e67cb29c22d165b5908185b4a79d82232c2234b#diff-697f70cdd88ba88fe77eebda60c7e143f6ad1286bca75017421e93ad84fb87dfR15

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/issues/3306#note_1993219288

**Comment by angelix** [comment]
> ref: https://github.com/Blockstream/green_android/blob/release_4.0.30/gradle/libs.versions.toml#L113
> 
> ref: [0e67cb2#diff-697f70cdd88ba88fe77eebda60c7e143f6ad1286bca75017421e93ad84fb87dfR15](https://github.com/Blockstream/green_android/commit/0e67cb29c22d165b5908185b4a79d82232c2234b#diff-697f70cdd88ba88fe77eebda60c7e143f6ad1286bca75017421e93ad84fb87dfR15)
> 
> /LE: fyi https://gitlab.com/fdroid/fdroiddata/-/issues/3306#note_1993219288

I'll move the dependency to `:gms` module, not used by f-droid flavor.

**Comment by angelix** [comment]
@licaon-kter Fixed in 04c9cf4a4286c4a2ac8ca65191adcceb36a10569 released as 4.0.31
