### ISSUE TITLE
The logic of Show and hide advanced options on create new account is inverse

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#221]
Hi,

The logic of Show and hide advanced options on create new account is inverse. The Show is hiding advanced options and Hide is showing advanced options.

Thanks.

**Comment by angelix** [comment]
Thank you for reporting. We did a refactor of the UI from Android Views to Jetpack Compose.

**Comment by angelix** [comment]
Fixed in latest release. 
Thanks for reporting.
