### ISSUE TITLE
Reproducibility of 4.0.35

### ISSUE THREAD

**Issue by xrviv** [Blockstream/green_android#226]
### Description

===== Begin Results =====
appId:          com.greenaddress.greenbits_android_wallet
signer:         32f9cc00b13fbeace51e2fb51df482044e42ad34a9bd912f179fedb16a42970e
apkVersionName: 4.0.35
apkVersionCode: 22000435
verdict:        
appHash:        08ab955932047f871c1ad8bae33db6a497c3b93f86a5f99cb77d6cf83f7e61f9
commit:         9d73b71e660ad67c5f29cba10a6775cb89faedb2

Diff:
Files /tmp/fromPlay_com.greenaddress.greenbits_android_wallet_22000435/assets/dexopt/baseline.prof and /tmp/fromBuild_com.greenaddress.greenbits_android_wallet_22000435/assets/dexopt/baseline.prof differ
Files /tmp/fromPlay_com.greenaddress.greenbits_android_wallet_22000435/classes.dex and /tmp/fromBuild_com.greenaddress.greenbits_android_wallet_22000435/classes.dex differ
Only in /tmp/fromPlay_com.greenaddress.greenbits_android_wallet_22000435/META-INF: GREENADD.RSA
Only in /tmp/fromPlay_com.greenaddress.greenbits_android_wallet_22000435/META-INF: GREENADD.SF
Only in /tmp/fromPlay_com.greenaddress.greenbits_android_wallet_22000435/META-INF: MANIFEST.MF

Revision, tag (and its signature):
object 9d73b71e660ad67c5f29cba10a6775cb89faedb2
type commit
tag release_4.0.35
tagger Angelos Veglektsis <angelos@aveworks.com> 1727701772 +0300
===== End Results =====

### Version

4.0.35

### Steps to reproduce

Run WalletScrutiny.com's [test.sh](https://gitlab.com/walletscrutiny/walletScrutinyCom/-/blob/master/test.sh?ref_type=heads) script on the Blockstream Green apk, we extracted from the phone.

### Expected behaviour

The results should come out as reproducible, with only signing related diffs.

### Actual behaviour

There are diffs on 2 files apart from the signing differences:

- baseline.prof
- classes.dex

### Screenshots

None.

### Device or machine

WalletScrutiny Build Server: Debian GNU/Linux 12 (bookworm)

### Additional info

[nosbin.com paste of diffoscope result](https://nosbin.com/nevent1qqs2tnusq833573fh8864zk603wzp9utl6l3vpw7d34vmeck5d43dmgpzemhxue69uhkzarvv9ejumn0wd68ytnvv9hxgqg4waehxw309ajkgetw9ehx7um5wghxcctwvsq3wamnwvaz7tmwdaehgu3wvekhgtnhd9azucnf0gq3gamnwvaz7tmwdaehgu3wdau8gu3wv3jhvqgswaehxw309ahx7um5wgh8w6twv5q3jamnwvaz7tmwdaehgu3w0fjkyetyv4jjucmvda6kgqghwaehxw309aex2mrp0yhxxatjwfjkuapwveukjqg5waehxw309aex2mrp0yhxgctdw4eju6t0qyt8wumn8ghj7un9d3shjtnwdaeky6tw9e3k7mgprfmhxue69uhhyetvv9ujummjv9hxwetsd9kxctnyv4mqzxrhwden5te0wfjkccte9eekummjwsh8xmmrd9skc4pwx84)

**Comment by angelix** [comment]
Did you try running `./gradlew uBK` before building?
Please try again with that.

**Comment by xrviv** [comment]
Hi, thank you for the response!

I will now try to do this!

**Comment by Giszmo** [comment]
Hi. I also gave it a try with our test script and got the same result.

We use uBK since January:

```
      ./gradlew useBlockstreamKeys;
      ./gradlew -x test clean assembleProductionGoogleRelease;
```

The culprit must be something else. The diffoscope looks benign except for the baseline profile which I don't feel qualified to call benign. The other diffs look like a mere ordering issue with two individual lines being swapped with other two lines.

**Comment by xrviv** [comment]
Closing this as new version 4.0.37 is now reproducible.
