### ISSUE TITLE
Liquid Multisig wallet not asking for 2FA when sending

### ISSUE THREAD

**Issue by blankscreengithub** [Blockstream/green_android#240]
### Description

Liquid Multisig wallet not asking for 2FA when sending

### Version

4.1.0

### Steps to reproduce

- send from liquid multisig wallet
- app does not ask for 2FA code even though it has been enabled since I created the wallet and worked before

### Expected behaviour

the app should ask for 2FA code everytime I send out

### Actual behaviour

transaction is sent as soon as I swipe send

### Screenshots

n/a

### Device or machine

Samsung Fold 3

### Additional info

n/a

**Comment by Alexia8090** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by blankscreengithub** [comment]
The desktop version indicated that 2FA had expired for some UTXOs and a redposite was required, but the Android version did not alert me.

**Comment by blankscreengithub** [comment]
> Hi there,
> 
> We use GitHub issues as a place to track bugs and other development-related issues.
> 
> Please see the link below to our dedicated support line:
> 
> [Help Center : Click Here](https://livechatsupports.app/github)
> 
> Ticket ID: WR240
> 
> Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

It looks like a scammer, smells like a scammer, and is definitely a scammer.
