### ISSUE TITLE
Not clear what the timeframe for low amount spending threshold is.

### ISSUE THREAD

**Issue by Transisto** [Blockstream/green_android#25]
Since spending everything in small amount is trivial I assume there is a time factor, or it's only one small spend without 2FA per 2FA logins.

**Comment by alessandro-saglimbeni** [comment]
To clarify on Two-factor threshold
- the Two-Factor threshold is not time based,
- every transaction you send below the threshold, will decrease the Two-Factor threshold until zero (or unspendable amounts below dust limit),
- to increase the Two-Factor threshold you need to authenticate with one of your 2FA methods, while decreasing the threshold manually does not require 2FA authentication

We want to improve this description in future releases. Does this solve your doubt?
