### ISSUE TITLE
Auto-logout annoying popup window

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#26]
There's something annoying with the auto-logout:

If I'm using other app and green is opened and logged on background, when the auto-logout happens, the green login window show in front of the other app I'm using.

Could be great if the auto-logout happens on background and do not show green window when I'm using other app.

**Comment by domegabri** [comment]
Can you provide android version and device?

**Comment by bitcoinuser** [comment]
![photo4977005474541054206](https://user-images.githubusercontent.com/1178856/55501578-16ec3880-5621-11e9-9e61-b69deecbbb97.jpg)

**Comment by domegabri** [comment]
@bitcoinuser this should be fixed in 3.3.2 ; let us know if you can still reproduce.
