### ISSUE TITLE
Still not working with Trezor

### ISSUE THREAD

**Issue by Hermetic** [Blockstream/green_android#28]
### Description

The latest update says the issue with trezor passphrases has been fixed. It still doesn't work for me.

### Version

Green Version 3.0.8

### Steps to reproduce

When I plug my trezor in there is indeed fields to enter my passphrase but when I enter it in both fields, and press 'continue', that still doesn't show me my trezor account balance for that passphrase. Instead it shows a message on my trezor asking "Sign message? cancel or confirm". I didn't create any transaction or message that needs to be signed. When I hit 'cancel' it says: "Error logging in with Hardware wallet". And when I, reluctantly, choose 'confirm' it gives me that same message.

### Expected behaviour

I expect it to show me my balance on the trezor and give me the option to spend from it or receive funds to it.

### Actual behaviour

explained above in 'Steps to reproduce'

### Device or machine

Trezor One 1.7.3
Google Pixel 2 phone 
Android 9

**Comment by LeoComandini** [comment]
> Instead it shows a message on my trezor asking "Sign message? cancel or confirm". I didn't create any transaction or message that needs to be signed. When I hit 'cancel' it says: "Error logging in with Hardware wallet". And when I, reluctantly, choose 'confirm' it gives me that same message.

When you log in with your account you need to authenticate with the server. The server sends you a challenge (displayed on the screen) to sign, so that you can prove the server you know the secret material to use your wallet.

"Error logging in with Hardware wallet" can be related to different failures, like unstable internet connection or cable not working properly, it might be worth trying another time.

If the problem persists, please reach us again here or at our support info@greenaddress.it.

**Comment by Hermetic** [comment]
> 
> When you log in with your account you need to authenticate with the server. The server sends you a challenge (displayed on the screen) to sign, so that you can prove the server you know the secret material to use your wallet.
>

I do see that code displayed on the trezor:
greenaddress.it
login [ code ]
Under that: "Sign message?"
with the buttons labelled: 'cancel' on the left and 'confirm' on the right

But I don't see it displayed on the Green Wallet screen, or anywhere else, so how can I confirm it is correct?

What the Green Wallet displays is: The Blockstream GREEN logo; under that an icon that looks like a trezor[is that code displayed on that tiny screen on that trezor icon? If so it is way too small to read]; and under that text which reads, "Please follow the instructions on your hardware wallet."

And as I said I have chosen 'confirm' anyway and it still doesn't show me the balance on the trezor account I am trying to access.

**Comment by domegabri** [comment]
If you are using the hardware wallet with other apps you won't see those balances on Green because it is totally different wallet. You should see zero if you are using it with Green/greenbits/greenaddress apps for the first time. If this is the case I recommend using a brand new device with Green that is not used elsewhere.

**Comment by Hermetic** [comment]
So after all this hassle of trying to get this to work I find out that green wallet doesn't support existing Trezor accounts. You (Blockstream) should be more clear about what exactly you mean by, "Full integration with Ledger and Trezor devices".  I still don't know... I thought it would be a convenient way of using my tezor instead of logging into a website on my desktop. 

But nevermind, now I don't care because I have no use for this if I can't use it to send funds from and receive funds to my trezor accounts. 

Thanks

**Comment by Hermetic** [comment]
> But I don't see it displayed on the Green Wallet screen, or anywhere else, so how can I confirm it is correct?

Or maybe I should leave this open because that confirmation thing mentioned above doesn't seem to be working.

**Comment by LeoComandini** [comment]
We are sorry this misunderstanding.

Green manages only its multisig outputs, which are protected by 2FA. This prevents an attacker from stealing your funds, even if he eavesdrops your mnemonic or accesses your hardware wallet.
If Green had single sig outputs mixed with multisig outputs, it would be misleading in term of security: some outputs would be protected by 2FA while others wouldn't, while looking identical from the UI.

Even though you cannot use Green to manage your single sig funds, you can still create a Green wallet and be protected both by your hardware wallet and 2FA.

We will fix the description on the website to be less confusing.

> But I don't see it displayed on the Green Wallet screen, or anywhere else, so how can I confirm it is correct?

The challenge you see on the screen is a random string given by the server for authentication purposes. You just have to check that is a 5-character string, if it's not correct for any reason, then you won't be able to log in your wallet, but it cannot be harmful to your wallet. For this reason we don't think it's useful to show the challenge on the GUI. However we will improve our documentation to make this step more clear.

**Comment by friendsofbitcoin** [comment]
Support for single sig (very important for lower fees and less dependency on Blockstreams server) would solve this issue. This is the reason why many cannot use this wallet. Thanks for creating an amazing wallet but IMHO single sig support should be a priority.

**Comment by greenaddress** [comment]
We have that planned. thanks!
