### ISSUE TITLE
can't access created wallet if you go back to create screen

### ISSUE THREAD

**Issue by zndtoshi** [Blockstream/green_android#3]
steps:
1. create wallet
2. press back on android
3. goes back to "create wallet" screen
4. no way to access the step 1 created wallet.

**Comment by RCasatta** [comment]
In the "create wallet" screen there should be a text "A wallet has been detected on this device Log in"  by tapping there you should be able to access to the previously created wallet

![Screenshot_1553084638](https://user-images.githubusercontent.com/6470319/54684043-850a0900-4b13-11e9-9b66-11a337b4f89c.png)

**Comment by zndtoshi** [comment]
Doesn't appear on my side. 
![54356097_318955428806113_839250027116232704_n](https://user-images.githubusercontent.com/47448562/54684262-78d67980-4b1c-11e9-83c7-17806dee1131.jpg)

**Comment by RCasatta** [comment]
Did you save the pin when creating a wallet?
If you haven't it is the expected behavious
(mnemonic is never saved in clear text on the device, only encrypted with the pin)

**Comment by zndtoshi** [comment]
I skipped the pin, yes. Ok I understand. Not intuitive though. Maybe force users to use pin?
PS: The app looks awesome and is great! 
PS2: Add a "Connect Hardware Wallet" button on main screen.

**Comment by RCasatta** [comment]
Thanks for the feedback, we will try to make it more clear
