### ISSUE TITLE
libwally does not exist

### ISSUE THREAD

**Issue by akshaynexus** [Blockstream/green_android#34]
### Description

error: package com.blockstream.libwally does not exist

### Version

master
### Steps to reproduce

clone repo
get gdk sdks
try running it via android studio
### Expected behaviour
should run and compile properly

### Actual behaviour
Causes the error mentioned above

### Device or machine

macOS Mojave,Android Studio 3.1.3
Build #AI-173.4819257, built on June 4, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.14.1

**Comment by domegabri** [comment]
Have you run the scripts to build gdk for the target architecture?
