### ISSUE TITLE
Crash at PIN login when using Tor

### ISSUE THREAD

**Issue by Transisto** [Blockstream/green_android#35]
App crash when simply logging with a PIN with TOR enabled.

Works fine with Tor disabled.

**Comment by domegabri** [comment]
Thanks. Next update will come with the fix

**Comment by domegabri** [comment]
Update on this:  to use the app with tor you need orbot running in parallel and the following proxy settings:

Socks5 proxy: 127.0.0.1
Socks5 port: 9050

**Comment by greenaddress** [comment]
hi @Transisto this should be fixed by version 3.1.0 - let us know if you still experience crashes with the app please
