### ISSUE TITLE
Recovery Transaction email link returns 404 error

### ISSUE THREAD

**Issue by 05nelsonm** [Blockstream/green_android#39]
### Description

Requesting a recovery transaction results in an email being sent containing a link to the recovery tool, but clicking the link returns a 404 page error.

### Version

3.1.0 (Fdroid)

### Steps to reproduce

Request recovery transaction
View email
Click provided link from email

### Expected behaviour

Should take you to the correct github page for the garecovery tool

### Actual behaviour

404 page error when going to https://github.com/greenaddress/garecovery.
### Device or machine

Samsung S9+ Android 8.1.0

**Comment by domegabri** [comment]
Thanks for reporting. It is working correctly for me now. Can you confirm?

**Comment by greenaddress** [comment]
@05nelsonm can you try to reproduce again? Perhaps it was a temporary network issue with github as https://github.com/greenaddress/garecovery seems available

**Comment by 05nelsonm** [comment]
Still sending me to:

https://github.com/greenaddress/garecovery.

With a "." At the end of the URL.

**Comment by 05nelsonm** [comment]
PIC of the email, as well as the page error that shows the link appended with a period.

https://send.firefox.com/download/a4a17479c9a6f083/#H0h5o6gxqDWoq0n479vSbQ
