### ISSUE TITLE
Add scan qr code to SPV pairing feature (i.e. knots)

### ISSUE THREAD

**Issue by greenaddress** [Blockstream/green_android#40]
Knots (a Bitcoin core distribution with more features) has added qr code for onion p2p pairing.

We should add a qrcode scanner in SPV settings

**Comment by simoanorak** [comment]
I think we should add NFC as well

**Comment by greenaddress** [comment]
@luke-jr implemented this in https://github.com/Blockstream/green_android/commit/24a0fc64dd1e01e737cc8f3ed2c1a7fbab429544 - should be out in the next release which should come out soon after some more testing

@simoanorak do you mean NFC share and/or tags of the onion url?
