### ISSUE TITLE
TX change not showing up in wallet

### ISSUE THREAD

**Issue by 05nelsonm** [Blockstream/green_android#41]
### Description

From Green Wallet I sent a TX from a p2wpkh address, to a p2wpkh (<--recipient) address and bech32 (<-- change output). The recipient address is showing up in the wallet, but the change address is not.

### Version

3.1.2

### Expected behaviour

Should show change addresses.

### Actual behaviour

Does not show address

### Device or machine

Android 8.1

**Comment by alessandro-saglimbeni** [comment]
> I sent a TX from a p2wpkh address, to a p2wpkh (<--recipient) address and bech32 (<-- change output)

How that you sent to a bech32 change output? How did you generate that address?

**Comment by domegabri** [comment]
We don't generate bech32 addresses for change. Currently we are showing the change address if a user logs in with a hardware wallet, since the devices require to confirm all outputs.
