### ISSUE TITLE
SPV: Getting Tor Connectivity Disabled Warning Even With Orbot

### ISSUE THREAD

**Issue by JeffVandrewJr** [Blockstream/green_android#42]
### Description

Under settings, under "Only Connect to Trusted Node for SPV", I put an onion address. Orbot is active, and Green is added as an app in Orbot. VPN mode is on. Green will not allow the onion address, stating "Tor Connectivity is Disabled!"

However, when I run Bitcoin Wallet for Android, I am successfully able to connect to my node via SPV using the exact same onion address, so I don't think it's an Orbot issue.

This is a v3 hidden service address if that matters.

I may be doing something really stupid, but I've been messing around for a while and can't seem to figure this one out.

### Version

3.1.3

### Steps to reproduce

Under settings, under "Only Connect to Trusted Node for SPV", I put an onion address. Orbot is active, and Green is added as an app in Orbot. VPN mode is on. Green will not allow the onion address, stating "Tor Connectivity is Disabled!"

### Expected behaviour

SPV connection over Tor.

### Actual behaviour
Error message as described above.

### Screenshots

N/A

### Device or machine

Xiaomi Mi Mix 2, Android 8.0.0 OPR1.70623.027, MIUI Global 10.2

### Additional info

None

**Comment by greenaddress** [comment]
For Tor support Green uses socks5 proxy explicitly.

We don't support the Orbot VPN mode as that is susceptible to accidental clearnet use and also doesn't tell the app to use the onion end point for the Green server

Please disable VPN mode for Green and enter the socks5 127.0.0.1 9050 in Green network settings (before login), you should now be able to use the onion for the green server (automatically) and enter any onion SPV paired node. 

Thanks

**Comment by JeffVandrewJr** [comment]
It seems to be syncing now, thanks!

And thank you for building in such an awesome feature. 

If I can make a feature request, it would be to make explicit in the error message where to find the network info screen after logging out. I looked all over for it before opening this ticket, and it also took me a while to find even after reading over your answer. 

I'm also happy to contribute a documentation PR with screenshots for SPV setup if/when you guys have docs posted.

Thanks again!

**Comment by JeffVandrewJr** [comment]
Actually I will close and open a separate issue.
