### ISSUE TITLE
Feature Request: Better Error Message for Tor SPV

### ISSUE THREAD

**Issue by JeffVandrewJr** [Blockstream/green_android#44]
### Description

When an onion address is entered for a trusted peer for SPV, the app throws an error telling the user to set the SOCKS5 Proxy. However, the screen to set that proxy info is hard to find; a shortcut from the settings would be a good idea.

### Version

3.1.3

### Steps to reproduce

Attempt SPV with a peer over tor before setting proxy info.

### Expected behaviour

Easier location of screen to enter proxy info.

### Actual behaviour

Hard to find proxy screen.

### Screenshots

N/A

### Device or machine

N/A

### Additional info
None

**Comment by domegabri** [comment]
message has been replaced with something more clear
