### ISSUE TITLE
[Feature Request] ability to copy recipient address from send page

### ISSUE THREAD

**Issue by 05nelsonm** [Blockstream/green_android#45]
### Description

If clicking on a link to say, a donation address, green address automatically opens to the send page. Would be convenient to be able to copy the address to view in a block explorer, or use a different wallet.

Some links that I am opening come from inside apps and the ability to long press the link to copy link address is not available.

### Version

3.1.3

**Comment by alessandro-saglimbeni** [comment]
You may want to clear the "Open by default" (or similar) option you may have have set for Green, which opens Green when a Bitcoin URI is clicked. You can do this from the system settings, look for Green's settings.

This way when you click on a Bitcoin URI you get the option to choose which wallet you want to use to open the link. Is this what you were trying to achieve?

**Comment by 05nelsonm** [comment]
I have that setup such that I choose to open link with. What I am saying wouod be a nice feature is on the send screen where choosing the amount to send and fee, a copy address button or something. You cannot highlight or select the send address on this screen (or atleast I cannot).

In app links do not have the same options (such as long press, copy url location) as opening a link in a browser. Was just using it as an example.

**Comment by angelix** [comment]
@05nelsonm issue is fixed with the new Send screen design.
