### ISSUE TITLE
Why the option to create a new wallet and restore wallet when already exist a wallet?

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#46]
Hi,

Blockstream Green has the option to restore or create a new wallet even with a wallet already created or restored. But as you can see you will need mneminic all time to login. 
I don't think it should have this option, because only complicate the UX (see image) and if users want to have two profiles of apps, Android has a function called DUAL APPS.

![photo5120902989379381258](https://user-images.githubusercontent.com/1178856/57995516-dfcecb00-7a98-11e9-9297-d7230debf98d.jpg)

**Comment by alessandro-saglimbeni** [comment]
Hi, thanks for your continous feedback. 

Indeed we are working on an improved UX for multi-wallet management, nonetheless we encourage using multiple accounts rather than multiple wallets, as managing different mnemonics is complex and advisable for advanced users only.
