### ISSUE TITLE
Cannot create wallet or restore wallet

### ISSUE THREAD

**Issue by friendsofbitcoin** [Blockstream/green_android#47]
### Description

Cannot create a new testnet wallet or mainet wallet from scratch . Tested both on VPN and local uplink. Not using TOR or proxy. Deleted and reinstalled app and tested again. Tested more than 6 times. Cannot restore 24 word seeds either created by blockstream green. Failure always occurs either after confirming the words or entering in the 24 words in restoration where app just hangs or shows an error message where I can close or send error report feedback 

### Version

green 3.1.3

### Device or machine

Android 7.1.1 build - 1 april 2018

HW - LG-M700F

### Additional info

I sent in a report with error logs 30 minutes ago via the app

**Comment by domegabri** [comment]
Thank you for reporting. I have checked the error logs. Its a known issue that has been fixed but it will be available in the next release.
