### ISSUE TITLE
[Feature Request] Allow custom gap limit if I'm using my own node

### ISSUE THREAD

**Issue by pavlenex** [Blockstream/green_android#49]
It would be extremely useful if you'd allow custom gap limit option that can be set up only if a user is using their own full node.

Use case: I'm using BTCPay as a merchant and want to see payments in my green wallet, because of the gap limit, I'm unable to see all of the transactions coming from my btcpay.

**Comment by petzsch** [comment]
Could this issue get some love from the blockstream devs? You offer a great afforderable HW wallet and many BTCPay merchants want to use it with the xpub in btcpay and the spending from their mobile device. But the gap limit problem is often getting in the way.

If merchants have a PC we can direct them to BTCPayServer.Vault but on mobile only situations this just doesn't cut it.

**Comment by remcoros** [comment]
BTCPay Server user here also. Setting up a (watch-only) wallet in Green (desktop / mobile) does not show any funds, because the initial gap is too large.

+1 to add a custom gap limit setting

**Comment by angelix** [comment]
@remcoros @petzsch @pavlenex thank you for this feature request.

I'll bump the priority on this.

**Comment by angelix** [comment]
Implemented in 702a6c6b6049ffe96affb017bb6da04cb6f7935f
Please wait until version 4.0.32 is released.

**Comment by pavlenex** [comment]
That's amazing @angelix looking forward to signalling BTCPay Users that green is now among recommended wallets. Thanks for implementing this.

**Comment by pavlenex** [comment]
Hey @angelix any idea how users could enable this feature on iOS? Is it implemented on iOS version of green?

**Comment by angelix** [comment]
> Hey [@angelix](https://github.com/angelix) any idea how users could enable this feature on iOS? Is it implemented on iOS version of green?

Hi @pavlenex , it's implemented in iOS too.
