### ISSUE TITLE
Insuficent funds even though there's more than enough funds [3.1.3]

### ISSUE THREAD

**Issue by pavlenex** [Blockstream/green_android#51]
### Description
The wallet shows an insufficient funds error even though I have more than enough of the required amount, as a result, I can't send from it.

### Version
* 3.13
### Steps to reproduce

My balance 0.00112556 BTC
Amount to pay: 0.00012484 BTC
Even with custom miner fee 1 satoshi/ vbyte it does not work

### Expected behaviour
Send the funds out of the wallet because I have enough funds to cover the cost.

### Actual behaviour
Insufficient funds

### Screenshots
![balance](https://user-images.githubusercontent.com/36959754/59349987-48693a80-8d1b-11e9-9a04-111d8be5d482.jpg)
![balance2](https://user-images.githubusercontent.com/36959754/59349988-48693a80-8d1b-11e9-94b5-d9f02aeb403f.jpg)

### Device or machine
Android, 7.0

### Additional info
The wallet was first connected to my own node, but then I turned it off, nothing improved, even tried changing rates but that ofc made no difference.

**Comment by pavlenex** [comment]
As suspected, it took quite a time for me being able to normally spend the funds. Unsure what caused it, server performance, but it's working again, will re-open if I notice it happening again.

**Comment by domegabri** [comment]
It was due to the fact that you had an unconfirmed transaction in the wallet. The change from do amount you sent was unconfirmed. App doesn't allow to spend unconfirmed coins. We are going to allow it in a future release, since it has caused confusion to many users.
