### ISSUE TITLE
[Feature] PIN dialog should have haptic feedback

### ISSUE THREAD

**Issue by prusnak** [Blockstream/green_android#53]
Normal keyboard uses haptic feedback (very short vibration) to signalize a keypress. PIN dialog in the app should use the same if possible because it is very unnatural when it's not present.

This is true for other software buttons (such as choosing the correct word from the seed when creating a new wallet).

**Comment by alessandro-saglimbeni** [comment]
Thank you for the suggestion we are tracking this improvement.

**Comment by domegabri** [comment]
9fe5b70738738a78e2cb554ec35e1a93cb562298
