### ISSUE TITLE
Can't recover Liquid funds from seed

### ISSUE THREAD

**Issue by CandleHater** [Blockstream/green_android#56]
### Description
I wasn't able to open my Liquid wallet anymore. After entering the correct pin it kept loading into infinity (I waited 30min). It only showed the loading animation, also after restarting the phone.
This occured the first time after I tryed to make an asset transaction with a 100 L-sat/kB fee. Afterwards I've not been able to login into the app again.

I then decided to recover the Liquid wallet by entering the seed words. This leaves me also with an infinite loading circle, without any kind of error message. I tryed this three times and on two phones by now.

### Version
3.1.8

### Steps to reproduce
Try to recover a Liquid wallet.

### Expected behaviour
Recovering a Liquid wallet.

### Actual behaviour
Endless loading after entering the seed and pressing the OK button.

### Device or machine
Nexus 7 and Pixel 2

**Comment by CandleHater** [comment]
With the latest update the behaviour described in "After entering the correct pin it kept loading into infinity" changed. Now I'm not even offered with the pin buttons. This is how the screen looks currently:

![screenshot-1563373489323](https://user-images.githubusercontent.com/50766841/61383771-9c81b480-a8af-11e9-96ee-6eef6026d923.jpg)

**Comment by domegabri** [comment]
Hi @CandleHater ,

Are you trying to login with the 6 digits PIN or Android native authentication?

**Comment by CandleHater** [comment]
I configured it with the 6 digits PIN.

**Comment by CandleHater** [comment]
I believe I've configured it with the 6 digits PIN. But if I'm mistaken, then I might know the origin. As my phones screen died, I've disabled the Android auth.

**Comment by domegabri** [comment]
I tried to restore a wallet using Android native authentication and than I disabled it from android settings. I can reproduce the behavior you experienced here:

> With the latest update the behaviour described in "After entering the correct pin it kept loading into infinity" changed. Now I'm not even offered with the pin buttons. This is how the screen looks currently:

**Comment by CandleHater** [comment]
Alright, so I guess I had native Android auth turned on. Also just tryed activating screen lock and opening  Green afterwards, but sadly this didn't help.

**Comment by domegabri** [comment]
I think that disabling the screen-lock is what breaks it. Even changing it likely causes troubles. We are investigating solutions. In the meantime you should be able to uninstall and restore the wallet with your mnemonic.

**Comment by CandleHater** [comment]
Please read the initial issue and title "Can't recover Liquid funds from seed" again, I'm not able to do so. That's the next bug I'm effected with. Tryed it again yesterday, this time on a Pixel 3 XL.

**Comment by domegabri** [comment]
> In the meantime you should be able to uninstall and restore the wallet with your mnemonic.

Have you tried this?

**Comment by CandleHater** [comment]
> Have you tried this?

As the title says "Can't recover Liquid funds from seed", yes. But after an update it worked fine and the issue can be closed.
