### ISSUE TITLE
Suggestion: easy way to switch between bitcoin and liquid wallets

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#57]
Hi,

1- I created a bitcoin wallet on Green app.
2- I created a liquid wallet on Green app.
3- I logged on Bitcoin wallet and went to wallets card and I don't see Liquid wallets on it.

Suggestion:

1- I think if users already created liquid and bitcoin walllet on Green app and go to cards on any wallet, should appear a message like: We detected that you have a liquid wallet on this device, do you want to list the liquid wallet here? 
2- So if the user choose yes, will show the liquid card with balance information.... 
3- If the user click on the liquid card, will show a popup to insert PIN or fingerprint and switch the network.

Obs: in my opinion the way it works now is not interesting as it's necessary to go to settings to switch network, change network, click save....

**Comment by domegabri** [comment]
Thank you for your feedback. We received many feedback on this and we are going to improve access to liquid in the next releases

**Comment by bitcoinuser** [comment]
It wasn't implemented in the way I would like, but I think it's fixed.
