### ISSUE TITLE
Suggestion: Do not allow custom keyboards for seed entry

### ISSUE THREAD

**Issue by abrkn** [Blockstream/green_android#59]
### Description

When restoring from seed, custom keyboards like Swiftkey, remain default. These keyboards transmit user entry over the Internet.

### Version

Latest from Play Store as of 2019-07-10

### Steps to reproduce

Restore from seed phrase

### Expected behaviour

Use passphrase entry keyboard

### Actual behaviour

Uses default keyboard

### Device or machine

Pixel 3

### Additional info

I've seen other wallets somehow lock the keyboard to a special passphrase entry one. I'm not an Android developer and don't know the technical terminology for this.

**Comment by angelix** [comment]
@abrkn an in-app keyboard is used for seed entry.
