### ISSUE TITLE
On accounts window should have a word like (used) or (not used)

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#6]
Hi,

I have three wallets, two of them has 0 balance but was used. (has transactions).When I go to accounts window I would like to see, without clicking on it, that if an account was already used or not.
So I think should have a word on account like (used) or (not used).

Thanks.

**Comment by bitschmidty** [comment]
@bitcoinuser what is your use case for the different wallets (accounts)? Seems like they are sort of one time use?

**Comment by bitcoinuser** [comment]
I have a 2of2 and two 2of3 accounts. Not a one time use. I just wanted to know (without clicking on it) if the account that I created was used anytime to send  or receive transactions.

**Comment by bitcoinuser** [comment]
Instead of used or not used, could show total of transactions on the account.
