### ISSUE TITLE
Suggestions of improvements on login window

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#62]
Hi,

1- I don't understand why Green show the login button in so small size.
2- I don't understand why Green show Create and Restore buttons when a wallet is already  detected on Green. If a wallet is already detected I see it's not possible to create or restore wallets, so why show these buttons?
3- Why Green doesn't have an option to delete the already detected wallet on the same place where there's an option to watch only login?

![photo5114110326802065399](https://user-images.githubusercontent.com/1178856/63558723-6fff2f00-c524-11e9-9bf2-b20b27a0627c.jpg)

**Comment by domegabri** [comment]
changes on this are coming in the next release!
