### ISSUE TITLE
Failed to continue on confirm PIN

### ISSUE THREAD

**Issue by caiofaustino** [Blockstream/green_android#67]
Probably related to #22, but I'm on version 3.2.1

### Description

Fresh install, trying to create a Testnet wallet. Confirmed seed words and I'm asked to create a PIN.
Both flows trying to either use existing device authentication or custom PIN don't proceed after asking for PIN confirmation.

It's weird that when choosing device authentication, it still goes back to the PIN screen asking for a custom PIN.

### Version

3.2.1

### Steps to reproduce

- Open App
- Choose Testnet
- Create new wallet
- Confirm
- Check mnemonic seed
- Click "Reuse Android Authentication"
- Confirm with fingerprint
- Choose PIN
- Type same PIN again
- Stuck, how to proceed?

### Expected behaviour

After retyping the PIN it should continue to next Fragment.

### Actual behaviour

Nothing happens. Cannot continue with wallet creation. No button to proceed.
Typing a wrong PIN does give me an error, but typing the same one nothing happens.

### Screenshots

![WhatsApp Image 2019-09-06 at 15 21 25](https://user-images.githubusercontent.com/3094935/64431899-a5c31c80-d0bb-11e9-98dc-70b19f57043f.jpeg)

### Device or machine

Nokia 7 Plus
Android 9 (Pie)

### Additional info

No logs, sorry. I can try to get a filtered logcat later if you tell me what to look for.

**Comment by domegabri** [comment]
Hi @caiofaustino , I couldn't reproduce your issue. We will make UI changes to solve this and address #56

**Comment by caiofaustino** [comment]
I just updated to 3.2.4 and I was able to create the wallet no problems.
