### ISSUE TITLE
When I login on watch only mode, Green doesn't remember the last opened wallet.

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#68]
When I login on watch only mode, Green doesn't remember the last opened wallet. Always open on main account.

**Comment by alessandro-saglimbeni** [comment]
Can you please elaborate on what you mean with 

> Green doesn't remember the last opened wallet.

Do you mean that you don't log into the last used account, and instead you are always led to Main account at login?

**Comment by bitcoinuser** [comment]
Yes, I'm always led on main account on login.

**Comment by vincenzopalazzo** [comment]
Hi @domegabri and @alessandro-saglimbeni.

I want to ask if this bug was resolved, if not I want to ask more details on reproducing the issue and I can try to help to fix this issue :smile:

**Comment by domegabri** [comment]
@bitcoinuser this appears to be fixed in 3.4.4, can you confirm?

**Comment by angelix** [comment]
@bitcoinuser fixed in latest release.
