### ISSUE TITLE
I think it should have a help button with faq on login window

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#69]
I think it should have a help button with faq on login window. (On top left)

![photo5177381538738841672](https://user-images.githubusercontent.com/1178856/64829206-db777200-d5a1-11e9-96e8-87e95c31a0f3.jpg)

**Comment by alessandro-saglimbeni** [comment]
Thanks for the feedback, we are tracking this improvement.

**Comment by angelix** [comment]
@bitcoinuser login screen is refactored. This issue is no longer valid. Please re-open if you have a new suggestion.
