### ISSUE TITLE
On settings (Switch Network) should have a text describing below what it means

### ISSUE THREAD

**Issue by bitcoinuser** [Blockstream/green_android#70]
On settings (Switch Network) should have a text describing below what it means, for example:

Switch Network
Login on another network like Liquid or Bitcoin testnet

**Comment by alessandro-saglimbeni** [comment]
We are working on an improvement related to this feature, we'll be happy to hear your feedback when it's going to be out.

**Comment by alessandro-saglimbeni** [comment]
Also related: https://github.com/Blockstream/green_android/issues/57
