### ISSUE TITLE
Can't connect to Internet

### ISSUE THREAD

**Issue by nharmon9** [Blockstream/green_android#74]
### Description

Trying to test in Android Studios connecting to my Regtest node but after setting the proxy it always says can't connect to internet??? 

### Version

Commit: 19b14ec0c8701b201bce1344b52a746f8fd802ca

### Device or machine

OSX 10.15.1

**Comment by domegabri** [comment]
Hello @nharmon9, if you want to test using android studio, you should connect to testnet.

Regtest requires an instance of our server which is not open source. We have a running instance of the server in testnet that we periodically deploy and maintain that can be used for testing and development.

**Comment by nharmon9** [comment]
Where is the Network data file located for Liquid?

**Comment by domegabri** [comment]
Hi @nharmon9 . at the moment there is no test environment for liquid. Our only running instance of the server is liquid mainnet. There's some network parameters here if this is what you were asking for: https://github.com/Blockstream/gdk/blob/master/src/network_parameters.cpp

Instances publicly available are only bitcoin mainnet, testnet, liquid mainnet.
