### ISSUE TITLE
CollapsingToolBarLayout scrolls up 2 far & disappears

### ISSUE THREAD

**Issue by 05nelsonm** [Blockstream/green_android#78]
### Version

master branch
Last commit: 1106d1c54e9d9b9a6c3759d95e329d0e1d5a4527

### Screenshots
![green_address_toolbar_disappears](https://user-images.githubusercontent.com/44778092/73602384-56392d80-4541-11ea-96f0-3ab9c0041bc3.gif)

### Device or machine

**Emulator Info**
Name: Pixel_3_API_29
CPU/ABI: Google Play Intel Atom (x86)
Path: /home/matthew/.android/avd/Pixel_3_API_29.avd
Target: google_apis_playstore [Google Play] (API level 29)
Skin: pixel_3
SD Card: 512 MB
fastboot.chosenSnapshotFile: 
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: pixel_3
hw.lcd.width: 1080
hw.initialOrientation: Portrait
image.androidVersion.api: 29
tag.id: google_apis_playstore
hw.mainKeys: no
hw.camera.front: emulated
avd.ini.displayname: Pixel 3 API 29
hw.gpu.mode: auto
hw.ramSize: 1536
PlayStore.enabled: true
fastboot.forceColdBoot: yes
hw.cpu.ncore: 4
hw.keyboard: yes
hw.sensors.proximity: yes
hw.dPad: no
hw.lcd.height: 2160
vm.heapSize: 256
skin.dynamic: yes
hw.device.manufacturer: Google
hw.gps: yes
hw.audioInput: yes
image.sysdir.1: system-images/android-29/google_apis_playstore/x86/
showDeviceFrame: yes
hw.camera.back: virtualscene
AvdId: Pixel_3_API_29
hw.lcd.density: 440
hw.arc: false
fastboot.forceChosenSnapshotBoot: no
fastboot.forceFastBoot: no
hw.trackBall: no
hw.battery: yes
hw.sdCard: yes
tag.display: Google Play
runtime.network.latency: none
disk.dataPartition.size: 8G
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes

**Comment by 05nelsonm** [comment]
Also occurs on my physical test device:

Samsun S9+
Android 8.1
CarbonOS ROM

**Comment by vincenzopalazzo** [comment]
Hi @domegabri, 

If the PRs are welcome, maybe this issue can have the tag "good first issue"? In my opinion, it is a good point where to start. (Today I start to read the code from this issue)
