### ISSUE TITLE
Invalid number format?

### ISSUE THREAD

**Issue by W9JYD** [Blockstream/green_android#79]
### Description

Cannot get SMS code. I entered my phone number correctly! 

### Version

IDK. Latest on F-Droid.

### Steps to reproduce

765 is a valid area code in the USA.
Get a Google Voice or textnow number with area code 765 (Indiana, where I live).
Sign up for SMS 2FA with that number.
Get error toast "Invalid phone number format"!
This should NOT happen! 765 is a VALID area code! 

### Expected behaviour

SMS 2FA goes through 

### Actual behaviour

"Invalid phone number format"
### Screenshots

(Not including due to personal info)

### Device or machine

Samsung Galaxy A10e, Android 9, Boost Mobile / Sprint 

### Additional info

https://en.wikipedia.org/wiki/Area_code_765

**Comment by domegabri** [comment]
Hello, phone numbers need to be formatted according to E.164 formatting. Examples here: https://support.twilio.com/hc/en-us/articles/223183008-Formatting-International-Phone-Numbers
