### ISSUE TITLE
Main App Icon much smaller on 4.4.2 Android

### ISSUE THREAD

**Issue by jeffrade** [Blockstream/green_android#8]
### Description

Downloaded on Android 4.4.2 (Samsung G S3) and the main app icon is much smaller relative to other apps. Downloaded on Android 7.0 (Samsung G S7) and the icon is normal size and looks good.

### Version

Version 3.0.6 on Play Store

### Steps to reproduce

 - Download and install the App from Play Store
 - Navigate to the App Icon on one of the main screens

### Expected behaviour

Icon should be similar size to other icons. Will standout better for users.

### Actual behaviour

Icon is too small

### Screenshots

![image](https://user-images.githubusercontent.com/1307806/54702830-a19f4480-4b05-11e9-81ed-a6d84e645d4e.png)

### Device or machine

Samsung G S3 4.4.2

### Additional info

Here is a good looking icon on Android 7.0 Samsung G S7

![image](https://user-images.githubusercontent.com/1307806/54702879-bb408c00-4b05-11e9-9a3f-d2137bc5a5fa.png)

**Comment by LeoComandini** [comment]
Thank you for detailed report. 

The issue should be fixed with b74fc76902c9708ab802798c437e0f6c8d5bdae6 and will be available in the next release.
