### ISSUE TITLE
Scanning invalid BIP21 QR code will crash the app

### ISSUE THREAD

**Issue by FrancisPouliot** [Blockstream/green_android#80]
### Description

Scanning invalid BIP21 QR code will crash the app

### Version

3.3.3 

### Steps to reproduce

Try scanning this

![image](https://user-images.githubusercontent.com/7997682/74275038-2a583d80-4ce1-11ea-9c57-fadb93d2d2b8.png)

From: liquidnetwork:VJL7E61zyx4M93gPgWMZvKEDrYssZqikmkYxoehKmzbJXeXP7DCRETbvnbmomxrEG942RKTkkhCrRHG6?amount=0.00000001&assetid=L-BTC

### Expected behaviour

Was expecting "Invalid Address"

### Actual behaviour

Pop-up appears every time
"Green keeps stopping" 
- App Info
- Close app
- Send feedback 

### Device or machine

Pixel 3

### Additional info

This other invalid URI gave me "invalid address", but the above URI just makes the app crash

liquidnetwork:<VJL7E61zyx4M93gPgWMZvKEDrYssZqikmkYxoehKmzbJXeXP7DCRETbvnbmomxrEG942RKTkkhCrRHG6>?amount=0.0000001&assetid=<6f0279e9ed041c3d710a9f57d0c02928416460c4b722ae3457a11eec381c526d>

**Comment by lvaccaro** [comment]
thanks @FrancisPouliot , 
a fix is introduces in https://github.com/Blockstream/gdk/commit/ceb083c3b4788c8b35b5c2d012b5588738273599 and released gdk v0.0.28: gdk dependency version updated in commit commit 75df2f059eafbf17358cc09ec8a67e518bc79196.
It will be available in the next green release v3.3.5 planned soon.

**Comment by domegabri** [comment]
Fix has been released. closing.
