### ISSUE TITLE
Green won't open Liquid BIP21 payment URI 

### ISSUE THREAD

**Issue by FrancisPouliot** [Blockstream/green_android#81]
### Description

In our app, we expose this BIP21 uri with link:

liquidnetwork:VJLHFaQf3ZfSFsrJE6nYM2qTyNvhi4ya1WvgFeAYQVuKKzNWbpiXC8tPFuymWaNHudgrRY35kYSjqUus?amount=0.00098172&label=Order%2043897%20-%20Francis%20Pouliot&assetid=6f0279e9ed041c3d710a9f57d0c02928416460c4b722ae3457a11eec381c526d

When clicking this on mobile, nothing happens. It works with Bitcoin, but lot Liquid. 

### Version

Latest 

### Steps to reproduce

I can share private link to a page of our app if required 

### Device or machine

Pixel 3

Not sure if this is a phone setting or an app config, or our BIP21 URI is wrong.

**Comment by lvaccaro** [comment]
Hi @FrancisPouliot , actually liquid network schema is not supported as data schema in the manifest to open the app. This looks like a really nice feature that requires to auto-select liquid network opening the app (in the case last selected network is bitcoin).

**Comment by FrancisPouliot** [comment]
Oh yes please! Will be useful when people have to a of assets in their wallet to make sure they don't pick the wrong one accidentally

**Comment by angelix** [comment]
@FrancisPouliot fixed in latest release. Please re-open if you have any problems.
