### ISSUE TITLE
Feature request: Support single signature option instead of just 2 of 2  

### ISSUE THREAD

**Issue by friendsofbitcoin** [Blockstream/green_android#87]
I regularly help onboard new users and this is the biggest reservation they have for using blockstream green and why many of them choose to use another wallet. They want a simple wallet with a compatible BIP39 seed words instead of a more complex 2 of 2 multisig custom signature wallet that is not compatible with any other wallet and can freeze their recovery for a window of nlocktime if blockstreams server ever goes down. 

Other concerns are larger size txs due to multisig causing block congestion and higher fees 

Other concerns is being forced to communicate with blockstreams servers even though we setup our full node with green.

Don't get me wrong, the 2 of 2 nlocktime feature is very interesting as it allows more advanced options like limits and 2fa but this should be optional for users on setup or account if they want to use these features. 

IMHO this should take priority over LN integration because many users I speak to are turning down your wallet right now principally because of this, but I don't want to tell you what you should prioritize and just here to give you some useful feedback since I deal with so many new users daily with onboarding. Thanks for a much improved wallet.

**Comment by domegabri** [comment]
We are actively working on this! stay tuned!

**Comment by skechboy** [comment]
Any ETA on this feature?

**Comment by skechboy** [comment]
> We are actively working on this! stay tuned!

Any ETA on this?

**Comment by friendsofbitcoin** [comment]
It pains me to say this , but I now have to stop recommending this wallet to friends and new users. This wallet has also been removed from the recommended list in the Bitcoin beginner Subreddit as well for these reasons:

1) There was just an outage in your server a few minutes ago and many users had their Bitcoin frozen and were freaking out. With a single signature wallet and common BIP39 seed backup I could advise them to simply import the seed into another wallet to use their bitcoin but not with Green because its multisig only and dependent upon Blockstream's servers 

Adam has promised this would be released soon about 1.5 years ago and IMHO the wait has been too long.

2) The ability to connect to our own full node feature has also been removed (why is that ?) 

Hopefully these issues will be resolved and I can begin to recommend this wallet again. Cheers.

**Comment by jgriffiths** [comment]
Hi,

Single sig is undergoing testing in the wallets, its is already fully supported in our underlying wallet library gdk, and is enabled for testnet in the desktop if you'd like to try it out there.

I believe we are planning to enable BTC mainnet in the next release which at the moment looks to be 1-2 weeks away.

**Comment by jgriffiths** [comment]
>     1. The ability to connect to our own full node feature has also been removed (why is that ?)

Apologies, this was not communicated properly. Own-node connections were previously supported in the android wallet only; with the arrival of single sig support we now have SPV in the underlying gdk library, available for all wallets to use. We plan to enable this for all wallets as soon as possible, there was some confusion between gdk vs individual wallet feature schedules causing us to miss the switch over thus it has not been seamless.

**Comment by friendsofbitcoin** [comment]
Thank you so much for the update. I tested the single sig version and its working great now. I am re-recommending this wallet as its an excellent wallet especially with adding native segwit address support as well.
