### ISSUE TITLE
ERROR: C library 'secp256k1' not found

### ISSUE THREAD

**Issue by omkar1117** [Blockstream/green_android#88]
### Description

subprojects/libwally-core-dbb5e11a76fc4e09ad6381ce695f740bc536ed9b/meson.build:33:0: ERROR: C library 'secp256k1' not found

### Version

master

### Steps to reproduce

After setting ANDROID_NDK and JAVA_HOME
cd app && ./prepare_gdk_clang.sh && cd ..
we are facing this issue

### Expected behaviour

Should install it successfully.

### Actual behaviour

|Executing subproject libwally-core method meson 
|
|Project name: libwally-core
|Project version: undefined
|C compiler for the build machine: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
|C compiler for the host machine: /home/office.zone/opakki/practice/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi19-clang (clang 9.0.8 "Android (5900059 based on r365631c) clang version 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 207d7abc1a2abf3ef8d4301736d6a7ebc224a290) (based on LLVM 9.0.8svn)")
|Message: Building libwally-core...
|Message: --- Failed to run command (stdout) ---
|Message: 
|Message: --- Failed to run command (stderr) ---
|Message: ./tools/autogen.sh: 2: ./tools/autogen.sh: autoreconf: not found
|tools/android_helpers.sh: line 63: ./configure: No such file or directory
|

subprojects/libwally-core-dbb5e11a76fc4e09ad6381ce695f740bc536ed9b/meson.build:33:0: ERROR: C library 'secp256k1' not found

### Screenshots

![BlueStream](https://user-images.githubusercontent.com/4657893/78249779-86cf2080-750c-11ea-9dcd-6c06328d9391.png)

### Device or machine

Ubuntu 18.04

### Additional info

[meson-log.txt](https://github.com/Blockstream/green_android/files/4421043/meson-log.txt)

**Comment by lvaccaro** [comment]
Hi @omkar1117 , `prepare_gdk_clang.sh` script fetches and build [gdk C library](https://github.com/Blockstream/gdk) . Follow your screenshots, It looks you have not the autoconf package installed. More info on gdk building could be found at https://github.com/Blockstream/gdk/blob/master/README.md

**Comment by domegabri** [comment]
@omkar1117 build instructions have been updated since this issue was opened
