### ISSUE TITLE
Liquid: recipient bech32 address in sent transaction displayed in bitcoin network format (bc1)

### ISSUE THREAD

**Issue by Sosthene00** [Blockstream/green_android#90]
### Description

The recipient bech32 address in sent transaction is displayed as a bitcoin mainnet "bc1" format, instead of the Liquid network format.

### Version

3.3.6 release

### Steps to reproduce

send some assets to a bech32 Liquid address, and inspect the transaction from the main screen.

### Expected behaviour

The address displayed in the recipient field should be in the Liquid format, ie begin with "ex1"

### Actual behaviour

The address is encoded in the Bitcoin mainnet format, ie begin with "bc1"

### Screenshots

![Screenshot from 2020-05-05 20-34-03](https://user-images.githubusercontent.com/11726747/81102650-3898ad00-8f10-11ea-82ac-92178412791b.png)

### Device or machine

Nexus 5x
Android version 8.1.0
LineageOS 15.1-20200217-NIGHTLY-bullhead

**Comment by domegabri** [comment]
Hello and thanks for the detailed report. Unfortunately I cannot reproduce your issue with the latest android release, which is 3.3.7. Do you mind giving it a try?

**Comment by Sosthene00** [comment]
Hi, unfortunately it seems that the package available on f-droid has not been updated to 3.3.7 yet. I tried to build the last version but about 30% of the test cases failed, I'm not sure why. I'll try to make it work and update to 3.3.7 asap

**Comment by weedcoder** [comment]
i'm on 3.3.7 android and i have bc1... recipient for lbtc and assets spends

**Comment by michel-foucault** [comment]
Hi same issue here with iOS`v3.3.6`
So not related to the android version, but if iOS version is not using BitcoinJ, the issue could be elsewhere 🤔

**Comment by lvaccaro** [comment]
Thanks for reporting, I report the issue to [GDK library](https://github.com/Blockstream/gdk) support; BitcoinJ is used only to local validation on android.

**Comment by Sosthene00** [comment]
Update: I updated to 3.3.7, the problem is still here

**Comment by domegabri** [comment]
ui changed so this doesn't apply anymore
