### ISSUE TITLE
CSV locktime 2 of 2 recovery 

### ISSUE THREAD

**Issue by friendsofbitcoin** [Blockstream/green_android#92]
One concern users have with their wallets is not having access to the required latest nlocktimes.zip to recover their Bitcoins if Blockstreams server is not available for whichever reason. Single Signatures being introduced will bypass this backup/recovery complexity altogether but I was wondering if you still had plans to implement CSV in Green as mentioned here for people wanting to use 2 of 2 multisig still?

https://blog.greenaddress.it/2018/03/26/two-factor-authentication-recovery/

**Comment by alessandro-saglimbeni** [comment]
Hi, yes! We are going to deploy CSV scripts for our multisig wallets, on Testnet first, as soon as we publish the first production release of the desktop app, which is currently in beta https://github.com/Blockstream/green_qt/releases

**Comment by friendsofbitcoin** [comment]
Ohhh, desktop app. Very nice.

**Comment by jgriffiths** [comment]
CSV is now active: https://blockstream.com/2021/01/25/en-blockstream-green-bitcoin-wallets-now-using-checksequenceverify-timelocks/

And the desktop wallet is released, so closing.
