### ISSUE TITLE
Stream full UTXOs for all types of inputs for Trezor

### ISSUE THREAD

**Issue by tsusanka** [Blockstream/green_android#93]
As you probably know a security issue* in the design of BIP-143 allows an attacker to lie about segwit input amounts and get the user to pay an unexpectedly high transaction fee. The problem affects all HWW vendors.

We are fixing this by making Trezor require the full UTXO for all types of inputs, so we can validate that the input amount is correct. We have introduced this change in firmware versions 2.3.1 and 1.9.1.

*) Details in our blogpost: https://blog.trezor.io/details-of-firmware-updates-for-trezor-one-version-1-9-1-and-trezor-model-t-version-2-3-1-1eba8f60f2dd

---

Might make sense to do with #89. Also as discussed in https://github.com/trezor/trezor-firmware/issues/1044 we will allow your derivation paths in our next firmware release.

---

Should I create a similar issue in https://github.com/Blockstream/green_ios?

**Comment by greenaddress** [comment]
@tsusanka thanks, we have added support for this in https://github.com/Blockstream/gdk/commit/0075fb351b0a44c5d2dca975e04b87dcbfa26ed3, when the apps upgrade to the latest version of gdk (next release) they will get this. However the real issue is that the paths we used are impacted until the next trezor firmware release in ~ august.

**Comment by tsusanka** [comment]
Ah, great. I just realized I did not open issue here so I wanted to fix that. Yes, sorry about the paths, we will work on the fix soon.

**Comment by domegabri** [comment]
@tsusanka this is done is latest release 3.3.9; also we have tested Trezor T firmware release 2.3.2 and it can successfully sign transactions built by Blockstream Green.

**Comment by tsusanka** [comment]
Thanks for letting me know!

**Comment by alessandro-saglimbeni** [comment]
Closing this one, should be fixed as release_3.3.9
