### ISSUE TITLE
Tiny survey about energy aware software practices.

### ISSUE THREAD

**Issue by moraispgsi** [Blockstream/green_android#98]
Dear contributors,

would you be willing to fill in a short 5-10 min survey (https://forms.gle/F3YwtLVKtk47yVhC9) about energy-efficient mobile development practices in the context of my master thesis? It's about raising awareness of software energy practices and about introducing a new open-source tool for helping in that regard. Your input would be greatly appreciated. Thanks a lot!

Ricardo Morais.

**Comment by vincenzopalazzo** [comment]
@moraispgsi I think you are in the wrong space, try to jump inside on telegram group to ask some questions here https://t.me/blockstream_green.

Good luck with your thesis

**Comment by jgriffiths** [comment]
Hi @moraispgsi,

I'm closing this issue as it is not the appropriate place to ask for research input (I did take the survey though). You may want to consider asking on a reddit programming comunity or hacker news.
